/* =============================================
   STEIRER PELLETS – PLZ Datenbank
   Alle Liefergebiete: Steiermark, Burgenland,
   Kärnten (Auswahl), NÖ (Auswahl)
   ============================================= */

const PLZ_DATA = {
  // ══════════════════════════════════════════════
  // STEIERMARK
  // ══════════════════════════════════════════════

  // ── Graz (Stadt) ──
  "8010": { ort: "Graz", region: "Graz", slug: "graz" },
  "8020": { ort: "Graz", region: "Graz", slug: "graz" },
  "8036": { ort: "Graz", region: "Graz", slug: "graz" },
  "8041": { ort: "Graz-Liebenau", region: "Graz", slug: "graz" },
  "8042": { ort: "Graz-St. Peter", region: "Graz", slug: "graz" },
  "8043": { ort: "Graz-Mariatrost", region: "Graz", slug: "graz" },
  "8044": { ort: "Graz-Mariatrost", region: "Graz", slug: "graz" },
  "8045": { ort: "Graz-Andritz", region: "Graz", slug: "graz" },
  "8046": { ort: "Graz-Stattegg", region: "Graz", slug: "graz" },
  "8047": { ort: "Graz-Ragnitz", region: "Graz", slug: "graz" },
  "8051": { ort: "Graz-Gösting", region: "Graz", slug: "graz" },
  "8052": { ort: "Graz-Wetzelsdorf", region: "Graz", slug: "graz" },
  "8053": { ort: "Graz-Neuhart", region: "Graz", slug: "graz" },
  "8054": { ort: "Graz-Straßgang", region: "Graz", slug: "graz" },
  "8055": { ort: "Graz-Puntigam", region: "Graz", slug: "graz" },
  "8063": { ort: "Eggersdorf bei Graz", region: "Graz", slug: "graz" },

  // ── Graz-Umgebung ──
  "8061": { ort: "St. Radegund bei Graz", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8062": { ort: "Kumberg", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8071": { ort: "Hausmannstätten", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8072": { ort: "Fernitz-Mellach", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8073": { ort: "Feldkirchen bei Graz", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8074": { ort: "Raaba-Grambach", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8075": { ort: "Hart bei Graz", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8076": { ort: "Vasoldsberg", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8081": { ort: "Heiligenkreuz am Waasen", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8082": { ort: "Kirchbach in Steiermark", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8083": { ort: "St. Stefan im Rosental", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8101": { ort: "Gratkorn", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8103": { ort: "Rein", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8111": { ort: "Judendorf-Straßengel", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8112": { ort: "Gratwein-Straßengel", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8113": { ort: "St. Bartholomä", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8114": { ort: "Stübing", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8120": { ort: "Peggau", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8121": { ort: "Deutschfeistritz", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8122": { ort: "Übelbach", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8124": { ort: "Frohnleiten", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8130": { ort: "Frohnleiten", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8131": { ort: "Pernegg an der Mur", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8141": { ort: "Premstätten", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8142": { ort: "Wundschuh", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8143": { ort: "Dobl-Zwaring", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8144": { ort: "Tobelbad", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8301": { ort: "Laßnitzhöhe", region: "Graz-Umgebung", slug: "graz-umgebung" },
  "8302": { ort: "Nestelbach bei Graz", region: "Graz-Umgebung", slug: "graz-umgebung" },

  // ── Voitsberg ──
  "8530": { ort: "Deutschlandsberg", region: "Voitsberg", slug: "voitsberg" },
  "8541": { ort: "Schwanberg", region: "Voitsberg", slug: "voitsberg" },
  "8542": { ort: "St. Peter im Sulmtal", region: "Voitsberg", slug: "voitsberg" },
  "8543": { ort: "St. Martin im Sulmtal", region: "Voitsberg", slug: "voitsberg" },
  "8544": { ort: "Pölfing-Brunn", region: "Voitsberg", slug: "voitsberg" },
  "8550": { ort: "Stainz", region: "Voitsberg", slug: "voitsberg" },
  "8551": { ort: "Wies", region: "Voitsberg", slug: "voitsberg" },
  "8552": { ort: "Eibiswald", region: "Voitsberg", slug: "voitsberg" },
  "8553": { ort: "St. Oswald ob Eibiswald", region: "Voitsberg", slug: "voitsberg" },
  "8554": { ort: "Soboth", region: "Voitsberg", slug: "voitsberg" },
  "8555": { ort: "St. Martin im Sulmtal", region: "Voitsberg", slug: "voitsberg" },
  "8570": { ort: "Voitsberg", region: "Voitsberg", slug: "voitsberg" },
  "8572": { ort: "Bärnbach", region: "Voitsberg", slug: "voitsberg" },
  "8573": { ort: "Söding-St. Johann", region: "Voitsberg", slug: "voitsberg" },
  "8580": { ort: "Köflach", region: "Voitsberg", slug: "voitsberg" },
  "8582": { ort: "Rosental an der Kainach", region: "Voitsberg", slug: "voitsberg" },
  "8583": { ort: "Edelschrott", region: "Voitsberg", slug: "voitsberg" },
  "8591": { ort: "Maria Lankowitz", region: "Voitsberg", slug: "voitsberg" },
  "8592": { ort: "Stallhofen", region: "Voitsberg", slug: "voitsberg" },

  // ── Deutschlandsberg ──
  "8501": { ort: "Lieboch", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8503": { ort: "St. Josef (Weststeiermark)", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8504": { ort: "Preding", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8505": { ort: "St. Nikolai im Sausal", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8510": { ort: "Stainz", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8511": { ort: "St. Stefan ob Stainz", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8521": { ort: "Wettmannstätten", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8522": { ort: "Groß St. Florian", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8523": { ort: "Frauental an der Laßnitz", region: "Deutschlandsberg", slug: "deutschlandsberg" },
  "8524": { ort: "Bad Gams", region: "Deutschlandsberg", slug: "deutschlandsberg" },

  // ── Leibnitz ──
  "8410": { ort: "Wildon", region: "Leibnitz", slug: "leibnitz" },
  "8411": { ort: "Hengsberg", region: "Leibnitz", slug: "leibnitz" },
  "8412": { ort: "Allerheiligen bei Wildon", region: "Leibnitz", slug: "leibnitz" },
  "8413": { ort: "St. Georgen an der Stiefing", region: "Leibnitz", slug: "leibnitz" },
  "8421": { ort: "Wolfsberg im Schwarzautal", region: "Leibnitz", slug: "leibnitz" },
  "8422": { ort: "St. Nikolai ob Draßling", region: "Leibnitz", slug: "leibnitz" },
  "8423": { ort: "St. Veit in der Südsteiermark", region: "Leibnitz", slug: "leibnitz" },
  "8424": { ort: "Gabersdorf", region: "Leibnitz", slug: "leibnitz" },
  "8430": { ort: "Leibnitz", region: "Leibnitz", slug: "leibnitz" },
  "8434": { ort: "Tillmitsch", region: "Leibnitz", slug: "leibnitz" },
  "8435": { ort: "Wagna", region: "Leibnitz", slug: "leibnitz" },
  "8442": { ort: "Kitzeck im Sausal", region: "Leibnitz", slug: "leibnitz" },
  "8443": { ort: "Gleinstätten", region: "Leibnitz", slug: "leibnitz" },
  "8444": { ort: "St. Andrä-Höch", region: "Leibnitz", slug: "leibnitz" },
  "8451": { ort: "Heimschuh", region: "Leibnitz", slug: "leibnitz" },
  "8452": { ort: "Gralla", region: "Leibnitz", slug: "leibnitz" },
  "8453": { ort: "St. Johann im Saggautal", region: "Leibnitz", slug: "leibnitz" },
  "8454": { ort: "Arnfels", region: "Leibnitz", slug: "leibnitz" },
  "8461": { ort: "Ehrenhausen an der Weinstraße", region: "Leibnitz", slug: "leibnitz" },
  "8462": { ort: "Gamlitz", region: "Leibnitz", slug: "leibnitz" },
  "8463": { ort: "Leutschach an der Weinstraße", region: "Leibnitz", slug: "leibnitz" },

  // ── Weiz ──
  "8160": { ort: "Weiz", region: "Weiz", slug: "weiz" },
  "8162": { ort: "Passail", region: "Weiz", slug: "weiz" },
  "8163": { ort: "Fladnitz an der Teichalm", region: "Weiz", slug: "weiz" },
  "8171": { ort: "St. Kathrein am Offenegg", region: "Weiz", slug: "weiz" },
  "8172": { ort: "Heilbrunn", region: "Weiz", slug: "weiz" },
  "8173": { ort: "Krottendorf-Gaisfeld", region: "Weiz", slug: "weiz" },
  "8181": { ort: "St. Ruprecht an der Raab", region: "Weiz", slug: "weiz" },
  "8182": { ort: "Puch bei Weiz", region: "Weiz", slug: "weiz" },
  "8183": { ort: "Floing", region: "Weiz", slug: "weiz" },
  "8184": { ort: "Anger", region: "Weiz", slug: "weiz" },
  "8190": { ort: "Birkfeld", region: "Weiz", slug: "weiz" },
  "8192": { ort: "Strallegg", region: "Weiz", slug: "weiz" },
  "8200": { ort: "Gleisdorf", region: "Weiz", slug: "weiz" },
  "8211": { ort: "Ilztal", region: "Weiz", slug: "weiz" },
  "8212": { ort: "Pischelsdorf am Kulm", region: "Weiz", slug: "weiz" },
  "8221": { ort: "Hirnsdorf", region: "Weiz", slug: "weiz" },
  "8222": { ort: "St. Johann bei Herberstein", region: "Weiz", slug: "weiz" },
  "8224": { ort: "Kaindorf", region: "Weiz", slug: "weiz" },
  "8225": { ort: "Pöllau", region: "Weiz", slug: "weiz" },

  // ── Hartberg-Fürstenfeld ──
  "8223": { ort: "Stubenberg am See", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8230": { ort: "Hartberg", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8232": { ort: "Grafendorf bei Hartberg", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8233": { ort: "Lafnitz", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8234": { ort: "Rohrbach an der Lafnitz", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8240": { ort: "Friedberg", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8241": { ort: "Dechantskirchen", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8242": { ort: "St. Lorenzen am Wechsel", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8243": { ort: "Pinggau", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8250": { ort: "Vorau", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8252": { ort: "Mönichwald", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8253": { ort: "Waldbach-Mönichwald", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8254": { ort: "Wenigzell", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8255": { ort: "St. Jakob im Walde", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8261": { ort: "Sinabelkirchen", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8262": { ort: "Ilz", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8263": { ort: "Großwilfersdorf", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8264": { ort: "Hainersdorf", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8265": { ort: "Großsteinbach", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8271": { ort: "Bad Waltersdorf", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8272": { ort: "Sebersdorf", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8273": { ort: "Ebersdorf", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8274": { ort: "Buch-St. Magdalena", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8280": { ort: "Fürstenfeld", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8282": { ort: "Loipersdorf bei Fürstenfeld", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8283": { ort: "Bad Blumau", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8284": { ort: "Ottendorf an der Rittschein", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8291": { ort: "Burgau", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8292": { ort: "Neudau", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8293": { ort: "Wörth an der Lafnitz", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8294": { ort: "Unterrohr", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },
  "8295": { ort: "St. Johann in der Haide", region: "Hartberg-Fürstenfeld", slug: "hartberg-fuerstenfeld" },

  // ── Südoststeiermark ──
  "8330": { ort: "Feldbach", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8331": { ort: "Kornberg bei Riegersburg", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8332": { ort: "Edelsbach bei Feldbach", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8333": { ort: "Riegersburg", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8334": { ort: "Löffelbach", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8341": { ort: "Paldau", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8342": { ort: "Gnas", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8343": { ort: "Trautmannsdorf in Oststeiermark", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8344": { ort: "Bad Gleichenberg", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8345": { ort: "Straden", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8350": { ort: "Fehring", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8353": { ort: "Kapfenstein", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8354": { ort: "St. Anna am Aigen", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8355": { ort: "Tieschen", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8361": { ort: "Hatzendorf", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8362": { ort: "Söchau", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8380": { ort: "Jennersdorf", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8382": { ort: "Mogersdorf", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8383": { ort: "Mühlgraben", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8384": { ort: "Minihof-Liebau", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8385": { ort: "Neuhaus am Klausenbach", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8490": { ort: "Bad Radkersburg", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8491": { ort: "Tieschen", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8492": { ort: "Halbenrain", region: "Südoststeiermark", slug: "suedoststeiermark" },
  "8493": { ort: "Klöch", region: "Südoststeiermark", slug: "suedoststeiermark" },

  // ── Leoben ──
  "8700": { ort: "Leoben", region: "Leoben", slug: "leoben" },
  "8701": { ort: "Leoben-Göss", region: "Leoben", slug: "leoben" },
  "8712": { ort: "Niklasdorf", region: "Leoben", slug: "leoben" },
  "8713": { ort: "St. Stefan ob Leoben", region: "Leoben", slug: "leoben" },
  "8714": { ort: "Kraubath an der Mur", region: "Leoben", slug: "leoben" },
  "8720": { ort: "Knittelfeld", region: "Leoben", slug: "leoben" },
  "8724": { ort: "Spielberg", region: "Leoben", slug: "leoben" },
  "8731": { ort: "Gaal", region: "Leoben", slug: "leoben" },
  "8732": { ort: "Seckau", region: "Leoben", slug: "leoben" },
  "8733": { ort: "St. Marein bei Knittelfeld", region: "Leoben", slug: "leoben" },
  "8734": { ort: "Großlobming", region: "Leoben", slug: "leoben" },
  "8740": { ort: "Zeltweg", region: "Leoben", slug: "leoben" },
  "8741": { ort: "Weißkirchen in Steiermark", region: "Leoben", slug: "leoben" },
  "8742": { ort: "Obdach", region: "Leoben", slug: "leoben" },
  "8750": { ort: "Judenburg", region: "Leoben", slug: "leoben" },
  "8753": { ort: "Fohnsdorf", region: "Leoben", slug: "leoben" },
  "8755": { ort: "St. Peter ob Judenburg", region: "Leoben", slug: "leoben" },
  "8756": { ort: "St. Georgen ob Judenburg", region: "Leoben", slug: "leoben" },
  "8770": { ort: "St. Michael in Obersteiermark", region: "Leoben", slug: "leoben" },
  "8773": { ort: "Kammern im Liesingtal", region: "Leoben", slug: "leoben" },
  "8775": { ort: "Kalwang", region: "Leoben", slug: "leoben" },
  "8782": { ort: "Wald am Schoberpaß", region: "Leoben", slug: "leoben" },
  "8783": { ort: "Gaishorn am See", region: "Leoben", slug: "leoben" },
  "8784": { ort: "Trieben", region: "Leoben", slug: "leoben" },
  "8785": { ort: "Hohentauern", region: "Leoben", slug: "leoben" },
  "8786": { ort: "Rottenmann", region: "Leoben", slug: "leoben" },
  "8790": { ort: "Eisenerz", region: "Leoben", slug: "leoben" },
  "8792": { ort: "St. Peter-Freienstein", region: "Leoben", slug: "leoben" },
  "8793": { ort: "Trofaiach", region: "Leoben", slug: "leoben" },
  "8794": { ort: "Vordernberg", region: "Leoben", slug: "leoben" },
  "8795": { ort: "Radmer", region: "Leoben", slug: "leoben" },

  // ── Bruck-Mürzzuschlag ──
  "8600": { ort: "Bruck an der Mur", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8605": { ort: "Kapfenberg", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8611": { ort: "St. Katharein an der Laming", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8612": { ort: "Tragöß-St. Katharein", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8613": { ort: "Marein bei Neumarkt", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8614": { ort: "Breitenau am Hochlantsch", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8616": { ort: "Gasen", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8621": { ort: "Thörl", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8622": { ort: "Etmißl", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8623": { ort: "Aflenz Kurort", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8624": { ort: "Turnau", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8625": { ort: "Turnau-Seewiesen", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8630": { ort: "Mariazell", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8632": { ort: "Gußwerk", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8634": { ort: "Wegscheid", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8635": { ort: "Gollrad", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8636": { ort: "St. Sebastian", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8641": { ort: "St. Marein im Mürztal", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8642": { ort: "St. Lorenzen im Mürztal", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8643": { ort: "Kindberg", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8644": { ort: "Mürzhofen", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8650": { ort: "Kindberg", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8652": { ort: "Kindberg-Aumühl", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8653": { ort: "Stanz im Mürztal", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8654": { ort: "Fischbach", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8655": { ort: "Langenwang", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8661": { ort: "Wartberg im Mürztal", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8662": { ort: "Mitterdorf im Mürztal", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8663": { ort: "Veitsch", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8664": { ort: "Niederaigen", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8665": { ort: "Langenwang", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8670": { ort: "Krieglach", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8671": { ort: "Alpl", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8672": { ort: "St. Jakob im Walde", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8673": { ort: "Ratten", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8674": { ort: "Rettenegg", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8680": { ort: "Mürzzuschlag", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8682": { ort: "Hönigsberg", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8684": { ort: "Spital am Semmering", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8685": { ort: "Steinhaus am Semmering", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8691": { ort: "Altenberg an der Rax", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8692": { ort: "Neuberg an der Mürz", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },
  "8693": { ort: "Mürzsteg", region: "Bruck-Mürzzuschlag", slug: "bruck-muerzzuschlag" },

  // ── Murtal ──
  "8721": { ort: "Apfelberg", region: "Murtal", slug: "murtal" },
  "8725": { ort: "St. Margarethen bei Knittelfeld", region: "Murtal", slug: "murtal" },
  "8760": { ort: "Pöls-Oberkurzheim", region: "Murtal", slug: "murtal" },
  "8761": { ort: "Pöls", region: "Murtal", slug: "murtal" },
  "8762": { ort: "Oberzeiring", region: "Murtal", slug: "murtal" },
  "8763": { ort: "Möderbrugg", region: "Murtal", slug: "murtal" },
  "8764": { ort: "Pusterwald", region: "Murtal", slug: "murtal" },
  "8765": { ort: "St. Peter ob Judenburg", region: "Murtal", slug: "murtal" },

  // ── Murau ──
  "8800": { ort: "Unzmarkt-Frauenburg", region: "Murau", slug: "murau" },
  "8811": { ort: "Scheifling", region: "Murau", slug: "murau" },
  "8812": { ort: "Mariahof", region: "Murau", slug: "murau" },
  "8813": { ort: "St. Lambrecht", region: "Murau", slug: "murau" },
  "8820": { ort: "Neumarkt in Steiermark", region: "Murau", slug: "murau" },
  "8822": { ort: "Mühlen", region: "Murau", slug: "murau" },
  "8823": { ort: "Laßnitz bei Murau", region: "Murau", slug: "murau" },
  "8831": { ort: "Niederwölz", region: "Murau", slug: "murau" },
  "8832": { ort: "Oberwölz", region: "Murau", slug: "murau" },
  "8833": { ort: "Teufenbach-Katsch", region: "Murau", slug: "murau" },
  "8834": { ort: "Schöder", region: "Murau", slug: "murau" },
  "8842": { ort: "St. Peter am Kammersberg", region: "Murau", slug: "murau" },
  "8843": { ort: "St. Georgen ob Murau", region: "Murau", slug: "murau" },
  "8844": { ort: "Schöder", region: "Murau", slug: "murau" },
  "8850": { ort: "Murau", region: "Murau", slug: "murau" },
  "8851": { ort: "Krakau", region: "Murau", slug: "murau" },
  "8852": { ort: "Stolzalpe", region: "Murau", slug: "murau" },
  "8853": { ort: "Ranten", region: "Murau", slug: "murau" },
  "8854": { ort: "Krakauhintermühlen", region: "Murau", slug: "murau" },
  "8861": { ort: "St. Georgen ob Murau", region: "Murau", slug: "murau" },
  "8862": { ort: "Stadl-Predlitz", region: "Murau", slug: "murau" },
  "8863": { ort: "Predlitz-Turrach", region: "Murau", slug: "murau" },

  // ── Liezen ──
  "8900": { ort: "Selzthal", region: "Liezen", slug: "liezen" },
  "8903": { ort: "Lassing", region: "Liezen", slug: "liezen" },
  "8904": { ort: "Ardning", region: "Liezen", slug: "liezen" },
  "8911": { ort: "Admont", region: "Liezen", slug: "liezen" },
  "8912": { ort: "Johnsbach", region: "Liezen", slug: "liezen" },
  "8913": { ort: "Weng im Gesäuse", region: "Liezen", slug: "liezen" },
  "8920": { ort: "Hieflau", region: "Liezen", slug: "liezen" },
  "8921": { ort: "Landl", region: "Liezen", slug: "liezen" },
  "8922": { ort: "Palfau", region: "Liezen", slug: "liezen" },
  "8923": { ort: "Wildalpen", region: "Liezen", slug: "liezen" },
  "8924": { ort: "Wildalpen-Hinterwildalpen", region: "Liezen", slug: "liezen" },
  "8930": { ort: "Liezen", region: "Liezen", slug: "liezen" },
  "8931": { ort: "Landl", region: "Liezen", slug: "liezen" },
  "8932": { ort: "St. Gallen", region: "Liezen", slug: "liezen" },
  "8933": { ort: "St. Gallen", region: "Liezen", slug: "liezen" },
  "8934": { ort: "Altenmarkt bei St. Gallen", region: "Liezen", slug: "liezen" },
  "8940": { ort: "Liezen", region: "Liezen", slug: "liezen" },
  "8942": { ort: "Wörschach", region: "Liezen", slug: "liezen" },
  "8943": { ort: "Aigen im Ennstal", region: "Liezen", slug: "liezen" },
  "8950": { ort: "Stainach-Pürgg", region: "Liezen", slug: "liezen" },
  "8951": { ort: "Trautenfels", region: "Liezen", slug: "liezen" },
  "8952": { ort: "Irdning-Donnersbachtal", region: "Liezen", slug: "liezen" },
  "8953": { ort: "Donnersbach", region: "Liezen", slug: "liezen" },
  "8954": { ort: "Donnersbachwald", region: "Liezen", slug: "liezen" },
  "8960": { ort: "Öblarn", region: "Liezen", slug: "liezen" },
  "8961": { ort: "Haus im Ennstal", region: "Liezen", slug: "liezen" },
  "8962": { ort: "Gröbming", region: "Liezen", slug: "liezen" },
  "8966": { ort: "Aich", region: "Liezen", slug: "liezen" },
  "8967": { ort: "Haus im Ennstal", region: "Liezen", slug: "liezen" },
  "8970": { ort: "Schladming", region: "Liezen", slug: "liezen" },
  "8971": { ort: "Rohrmoos-Untertal", region: "Liezen", slug: "liezen" },
  "8972": { ort: "Ramsau am Dachstein", region: "Liezen", slug: "liezen" },
  "8982": { ort: "Tauplitz", region: "Liezen", slug: "liezen" },
  "8983": { ort: "Bad Mitterndorf", region: "Liezen", slug: "liezen" },
  "8984": { ort: "Kainisch", region: "Liezen", slug: "liezen" },
  "8990": { ort: "Bad Aussee", region: "Liezen", slug: "liezen" },
  "8992": { ort: "Altaussee", region: "Liezen", slug: "liezen" },
  "8993": { ort: "Grundlsee", region: "Liezen", slug: "liezen" },

  // ══════════════════════════════════════════════
  // BURGENLAND
  // ══════════════════════════════════════════════

  // ── Eisenstadt (Stadt) ──
  "7000": { ort: "Eisenstadt", region: "Eisenstadt", slug: "eisenstadt" },

  // ── Eisenstadt-Umgebung ──
  "7011": { ort: "Siegendorf", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7013": { ort: "Klingenbach", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7021": { ort: "Draßburg", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7022": { ort: "Schattendorf", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7023": { ort: "Zemendorf-Stöttera", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7024": { ort: "Hirm", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7031": { ort: "Krensdorf", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7032": { ort: "Sigleß", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7033": { ort: "Pöttsching", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7034": { ort: "Zillingtal", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7035": { ort: "Steinbrunn", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7041": { ort: "Wulkaprodersdorf", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7051": { ort: "Großhöflein", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7052": { ort: "Müllendorf", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7053": { ort: "Hornstein", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7061": { ort: "Trausdorf an der Wulka", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7062": { ort: "St. Margarethen im Burgenland", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7063": { ort: "Oggau am Neusiedler See", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },
  "7064": { ort: "Oslip", region: "Eisenstadt-Umgebung", slug: "eisenstadt-umgebung" },

  // ── Rust ──
  "7071": { ort: "Rust", region: "Rust", slug: "rust" },

  // ── Mattersburg ──
  "7201": { ort: "Neudörfl", region: "Mattersburg", slug: "mattersburg" },
  "7202": { ort: "Bad Sauerbrunn", region: "Mattersburg", slug: "mattersburg" },
  "7203": { ort: "Wiesen", region: "Mattersburg", slug: "mattersburg" },
  "7210": { ort: "Mattersburg", region: "Mattersburg", slug: "mattersburg" },
  "7212": { ort: "Forchtenstein", region: "Mattersburg", slug: "mattersburg" },

  // ── Oberpullendorf ──
  "7301": { ort: "Deutschkreutz", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7302": { ort: "Nikitsch", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7304": { ort: "Großwarasdorf", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7311": { ort: "Neckenmarkt", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7312": { ort: "Horitschon", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7321": { ort: "Lackendorf", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7322": { ort: "Lackenbach", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7323": { ort: "Ritzing", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7331": { ort: "Weppersdorf", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7332": { ort: "Kobersdorf", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7341": { ort: "Markt St. Martin", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7342": { ort: "Kaisersdorf", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7343": { ort: "Neutal", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7350": { ort: "Oberpullendorf", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7361": { ort: "Lutzmannsburg", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7371": { ort: "Oberloisdorf", region: "Oberpullendorf", slug: "oberpullendorf" },
  "7372": { ort: "Draßmarkt", region: "Oberpullendorf", slug: "oberpullendorf" },

  // ── Neusiedl am See ──
  "2424": { ort: "Zurndorf", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7100": { ort: "Neusiedl am See", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7111": { ort: "Parndorf", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7121": { ort: "Weiden am See", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7122": { ort: "Gols", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7123": { ort: "Mönchhof", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7131": { ort: "Halbturn", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7132": { ort: "Frauenkirchen", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7141": { ort: "Podersdorf am See", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7142": { ort: "Illmitz", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7143": { ort: "Apetlon", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7151": { ort: "Wallern im Burgenland", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7152": { ort: "Pamhagen", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7161": { ort: "St. Andrä am Zicksee", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7162": { ort: "Tadten", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7163": { ort: "Andau", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7164": { ort: "Nickelsdorf", region: "Neusiedl am See", slug: "neusiedl-am-see" },
  "7165": { ort: "Deutschjahrndorf", region: "Neusiedl am See", slug: "neusiedl-am-see" },

  // ── Güssing ──
  "7521": { ort: "Eberau", region: "Güssing", slug: "guessing" },
  "7522": { ort: "Strem", region: "Güssing", slug: "guessing" },
  "7523": { ort: "Heiligenbrunn", region: "Güssing", slug: "guessing" },
  "7524": { ort: "Moschendorf", region: "Güssing", slug: "guessing" },
  "7525": { ort: "Rauchwart", region: "Güssing", slug: "guessing" },
  "7531": { ort: "Kemeten", region: "Güssing", slug: "guessing" },
  "7532": { ort: "Litzelsdorf", region: "Güssing", slug: "guessing" },
  "7533": { ort: "Ollersdorf im Burgenland", region: "Güssing", slug: "guessing" },
  "7534": { ort: "Olbendorf", region: "Güssing", slug: "guessing" },
  "7535": { ort: "Neuberg im Burgenland", region: "Güssing", slug: "guessing" },
  "7536": { ort: "Güttenbach", region: "Güssing", slug: "guessing" },
  "7537": { ort: "Stinatz", region: "Güssing", slug: "guessing" },
  "7540": { ort: "Güssing", region: "Güssing", slug: "guessing" },
  "7542": { ort: "Gerersdorf-Sulz", region: "Güssing", slug: "guessing" },
  "7543": { ort: "Kukmirn", region: "Güssing", slug: "guessing" },
  "7551": { ort: "Stegersbach", region: "Güssing", slug: "guessing" },
  "7552": { ort: "Stegersbach", region: "Güssing", slug: "guessing" },
  "7553": { ort: "Ollersdorf", region: "Güssing", slug: "guessing" },
  "7554": { ort: "Tobaj", region: "Güssing", slug: "guessing" },
  "7555": { ort: "St. Michael im Burgenland", region: "Güssing", slug: "guessing" },
  "7561": { ort: "Heiligenkreuz im Lafnitztal", region: "Güssing", slug: "guessing" },
  "7562": { ort: "Eltendorf", region: "Güssing", slug: "guessing" },
  "7563": { ort: "Königsdorf", region: "Güssing", slug: "guessing" },
  "7564": { ort: "Dobersdorf", region: "Güssing", slug: "guessing" },

  // ── Oberwart ──
  "7400": { ort: "Oberwart", region: "Oberwart", slug: "oberwart" },
  "7411": { ort: "Markt Allhau", region: "Oberwart", slug: "oberwart" },
  "7412": { ort: "Wolfau", region: "Oberwart", slug: "oberwart" },
  "7413": { ort: "Rechnitz", region: "Oberwart", slug: "oberwart" },
  "7421": { ort: "Mönichkirchen", region: "Oberwart", slug: "oberwart" },
  "7422": { ort: "Riedlingsdorf", region: "Oberwart", slug: "oberwart" },
  "7423": { ort: "Pinkafeld", region: "Oberwart", slug: "oberwart" },
  "7431": { ort: "Bad Tatzmannsdorf", region: "Oberwart", slug: "oberwart" },
  "7432": { ort: "Oberschützen", region: "Oberwart", slug: "oberwart" },
  "7433": { ort: "Mariasdorf", region: "Oberwart", slug: "oberwart" },
  "7434": { ort: "Bernstein", region: "Oberwart", slug: "oberwart" },
  "7435": { ort: "Unterkohlstätten", region: "Oberwart", slug: "oberwart" },
  "7441": { ort: "Kemeten", region: "Oberwart", slug: "oberwart" },
  "7442": { ort: "Lockenhaus", region: "Oberwart", slug: "oberwart" },
  "7443": { ort: "Liebing", region: "Oberwart", slug: "oberwart" },
  "7444": { ort: "Mannersdorf an der Rabnitz", region: "Oberwart", slug: "oberwart" },
  "7451": { ort: "Oberkohlstätten", region: "Oberwart", slug: "oberwart" },
  "7452": { ort: "Unterpullendorf", region: "Oberwart", slug: "oberwart" },
  "7453": { ort: "Steinberg-Dörfl", region: "Oberwart", slug: "oberwart" },
  "7461": { ort: "Stadtschlaining", region: "Oberwart", slug: "oberwart" },
  "7471": { ort: "Rechnitz", region: "Oberwart", slug: "oberwart" },
  "7472": { ort: "Schachendorf", region: "Oberwart", slug: "oberwart" },
  "7473": { ort: "Hannersdorf", region: "Oberwart", slug: "oberwart" },
  "7474": { ort: "Deutsch Schützen-Eisenberg", region: "Oberwart", slug: "oberwart" },

  // ── Jennersdorf ──
  "7540": { ort: "Güssing", region: "Güssing", slug: "guessing" },
  "7542": { ort: "Gerersdorf-Sulz", region: "Güssing", slug: "guessing" },

  // ══════════════════════════════════════════════
  // KÄRNTEN (Auswahl)
  // ══════════════════════════════════════════════

  // ── Wolfsberg ──
  "9400": { ort: "Wolfsberg", region: "Wolfsberg", slug: "wolfsberg" },
  "9411": { ort: "St. Michael ob Bleiburg", region: "Wolfsberg", slug: "wolfsberg" },
  "9412": { ort: "Wolfsberg-St. Stefan", region: "Wolfsberg", slug: "wolfsberg" },
  "9413": { ort: "St. Gertraud", region: "Wolfsberg", slug: "wolfsberg" },
  "9421": { ort: "Eitweg", region: "Wolfsberg", slug: "wolfsberg" },
  "9422": { ort: "Maria Rojach", region: "Wolfsberg", slug: "wolfsberg" },
  "9431": { ort: "St. Stefan im Lavanttal", region: "Wolfsberg", slug: "wolfsberg" },
  "9432": { ort: "Frantschach-St. Gertraud", region: "Wolfsberg", slug: "wolfsberg" },
  "9433": { ort: "St. Andrä im Lavanttal", region: "Wolfsberg", slug: "wolfsberg" },
  "9441": { ort: "Twimberg", region: "Wolfsberg", slug: "wolfsberg" },
  "9442": { ort: "Preitenegg", region: "Wolfsberg", slug: "wolfsberg" },
  "9443": { ort: "Frantschach", region: "Wolfsberg", slug: "wolfsberg" },
  "9444": { ort: "Gräbern", region: "Wolfsberg", slug: "wolfsberg" },
  "9451": { ort: "Preitenegg", region: "Wolfsberg", slug: "wolfsberg" },
  "9461": { ort: "Wolfsberg", region: "Wolfsberg", slug: "wolfsberg" },
  "9462": { ort: "Bad St. Leonhard im Lavanttal", region: "Wolfsberg", slug: "wolfsberg" },
  "9463": { ort: "Reichenfels", region: "Wolfsberg", slug: "wolfsberg" },

  // ── Völkermarkt ──
  "9100": { ort: "Völkermarkt", region: "Völkermarkt", slug: "voelkermarkt" },
  "9102": { ort: "Mittlern", region: "Völkermarkt", slug: "voelkermarkt" },
  "9103": { ort: "Diex", region: "Völkermarkt", slug: "voelkermarkt" },
  "9111": { ort: "Haimburg", region: "Völkermarkt", slug: "voelkermarkt" },
  "9112": { ort: "Griffen", region: "Völkermarkt", slug: "voelkermarkt" },
  "9113": { ort: "Ruden", region: "Völkermarkt", slug: "voelkermarkt" },
  "9121": { ort: "Tainach", region: "Völkermarkt", slug: "voelkermarkt" },
  "9122": { ort: "St. Kanzian am Klopeiner See", region: "Völkermarkt", slug: "voelkermarkt" },
  "9123": { ort: "St. Primus", region: "Völkermarkt", slug: "voelkermarkt" },
  "9125": { ort: "Kühnsdorf", region: "Völkermarkt", slug: "voelkermarkt" },
  "9131": { ort: "Grafenstein", region: "Völkermarkt", slug: "voelkermarkt" },
  "9132": { ort: "Gallizien", region: "Völkermarkt", slug: "voelkermarkt" },
  "9133": { ort: "Sittersdorf", region: "Völkermarkt", slug: "voelkermarkt" },
  "9135": { ort: "Eisenkappel-Vellach", region: "Völkermarkt", slug: "voelkermarkt" },
  "9141": { ort: "Eberndorf", region: "Völkermarkt", slug: "voelkermarkt" },
  "9142": { ort: "Globasnitz", region: "Völkermarkt", slug: "voelkermarkt" },
  "9143": { ort: "St. Michael ob Bleiburg", region: "Völkermarkt", slug: "voelkermarkt" },
  "9150": { ort: "Bleiburg", region: "Völkermarkt", slug: "voelkermarkt" },
  "9155": { ort: "Neuhaus", region: "Völkermarkt", slug: "voelkermarkt" },

  // ── Sankt Veit an der Glan ──
  "9300": { ort: "St. Veit an der Glan", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9311": { ort: "Kraig", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9312": { ort: "Frauenstein", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9313": { ort: "St. Georgen am Längsee", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9314": { ort: "Launsdorf", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9321": { ort: "Kappel am Krappfeld", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9322": { ort: "Micheldorf", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9330": { ort: "Althofen", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9334": { ort: "Guttaring", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9335": { ort: "Hüttenberg", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9341": { ort: "Straßburg", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9342": { ort: "Gurk", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9343": { ort: "Zweinitz", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9344": { ort: "Weitensfeld im Gurktal", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9345": { ort: "Kleinglödnitz", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9346": { ort: "Glödnitz", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9360": { ort: "Friesach", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9361": { ort: "St. Salvator", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9362": { ort: "Grades", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9363": { ort: "Metnitz", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9371": { ort: "Brückl", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9372": { ort: "Eberstein", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9373": { ort: "Klein St. Paul", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9374": { ort: "Wieting", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9375": { ort: "Hüttenberg", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },
  "9376": { ort: "Knappenberg", region: "Sankt Veit an der Glan", slug: "sankt-veit-an-der-glan" },

  // ── Klagenfurt (Stadt) ──
  "9010": { ort: "Klagenfurt am Wörthersee", region: "Klagenfurt", slug: "klagenfurt" },
  "9020": { ort: "Klagenfurt am Wörthersee", region: "Klagenfurt", slug: "klagenfurt" },
  "9021": { ort: "Klagenfurt am Wörthersee", region: "Klagenfurt", slug: "klagenfurt" },
  "9061": { ort: "Klagenfurt-Wölfnitz", region: "Klagenfurt", slug: "klagenfurt" },
  "9062": { ort: "Klagenfurt-Viktring", region: "Klagenfurt", slug: "klagenfurt" },
  "9063": { ort: "Maria Saal", region: "Klagenfurt", slug: "klagenfurt" },
  "9064": { ort: "Pischeldorf", region: "Klagenfurt", slug: "klagenfurt" },
  "9065": { ort: "Ebenthal in Kärnten", region: "Klagenfurt", slug: "klagenfurt" },
  "9073": { ort: "Klagenfurt-Viktring", region: "Klagenfurt", slug: "klagenfurt" },

  // ── Klagenfurt-Land ──
  "9071": { ort: "Köttmannsdorf", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9072": { ort: "Ludmannsdorf", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9074": { ort: "Keutschach am See", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9081": { ort: "Reifnitz", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9082": { ort: "Maria Wörth", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9161": { ort: "Maria Rain", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9162": { ort: "Strau", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9163": { ort: "Unterbergen", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9170": { ort: "Ferlach", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9201": { ort: "Krumpendorf am Wörthersee", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9210": { ort: "Pörtschach am Wörthersee", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9220": { ort: "Velden am Wörthersee", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9231": { ort: "Köstenberg", region: "Klagenfurt-Land", slug: "klagenfurt-land" },
  "9232": { ort: "Rosegg", region: "Klagenfurt-Land", slug: "klagenfurt-land" },

  // ══════════════════════════════════════════════
  // NIEDERÖSTERREICH (Auswahl)
  // ══════════════════════════════════════════════

  // ── Baden ──
  "2500": { ort: "Baden bei Wien", region: "Baden", slug: "baden" },
  "2511": { ort: "Pfaffstätten", region: "Baden", slug: "baden" },
  "2512": { ort: "Tribuswinkel", region: "Baden", slug: "baden" },
  "2514": { ort: "Traiskirchen", region: "Baden", slug: "baden" },
  "2521": { ort: "Trumau", region: "Baden", slug: "baden" },
  "2522": { ort: "Oberwaltersdorf", region: "Baden", slug: "baden" },
  "2523": { ort: "Tattendorf", region: "Baden", slug: "baden" },
  "2524": { ort: "Teesdorf", region: "Baden", slug: "baden" },
  "2525": { ort: "Günselsdorf", region: "Baden", slug: "baden" },
  "2531": { ort: "Gaaden", region: "Baden", slug: "baden" },
  "2532": { ort: "Heiligenkreuz", region: "Baden", slug: "baden" },
  "2533": { ort: "Klausen-Leopoldsdorf", region: "Baden", slug: "baden" },
  "2534": { ort: "Alland", region: "Baden", slug: "baden" },
  "2540": { ort: "Bad Vöslau", region: "Baden", slug: "baden" },
  "2542": { ort: "Kottingbrunn", region: "Baden", slug: "baden" },
  "2544": { ort: "Leobersdorf", region: "Baden", slug: "baden" },
  "2551": { ort: "Enzesfeld-Lindabrunn", region: "Baden", slug: "baden" },
  "2552": { ort: "Hirtenberg", region: "Baden", slug: "baden" },
  "2560": { ort: "Berndorf", region: "Baden", slug: "baden" },
  "2563": { ort: "Pottenstein", region: "Baden", slug: "baden" },
  "2564": { ort: "Weissenbach an der Triesting", region: "Baden", slug: "baden" },
  "2565": { ort: "Neuhaus", region: "Baden", slug: "baden" },
  "2571": { ort: "Altenmarkt an der Triesting", region: "Baden", slug: "baden" },
  "2572": { ort: "Kaumberg", region: "Baden", slug: "baden" },
  "2601": { ort: "Sollenau", region: "Baden", slug: "baden" },
  "2602": { ort: "Blumau-Neurißhof", region: "Baden", slug: "baden" },
  "2603": { ort: "Felixdorf", region: "Baden", slug: "baden" },
  "2604": { ort: "Theresienfeld", region: "Baden", slug: "baden" },

  // ── Bruck an der Leitha ──
  "2340": { ort: "Mödling", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2345": { ort: "Brunn am Gebirge", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2404": { ort: "Petronell-Carnuntum", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2405": { ort: "Bad Deutsch-Altenburg", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2410": { ort: "Hainburg an der Donau", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2412": { ort: "Wolfsthal", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2413": { ort: "Berg", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2421": { ort: "Kittsee", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2422": { ort: "Pama", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2431": { ort: "Enzersdorf an der Fischa", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2432": { ort: "Schwadorf", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2433": { ort: "Margarethen am Moos", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2434": { ort: "Götzendorf an der Leitha", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2435": { ort: "Ebergassing", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2440": { ort: "Gramatneusiedl", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2441": { ort: "Mitterndorf an der Fischa", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2443": { ort: "Loretto", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2444": { ort: "Seibersdorf", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2451": { ort: "Hof am Leithaberge", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2452": { ort: "Mannersdorf am Leithagebirge", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2453": { ort: "Sommerein", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2454": { ort: "Trautmannsdorf an der Leitha", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2460": { ort: "Bruck an der Leitha", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2462": { ort: "Wilfleinsdorf", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2463": { ort: "Gallbrunn", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2464": { ort: "Göttlesbrunn-Arbesthal", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2465": { ort: "Höflein", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2471": { ort: "Rohrau", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2472": { ort: "Prellenkirchen", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2473": { ort: "Potzneusiedl", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2481": { ort: "Achau", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2482": { ort: "Münchendorf", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2483": { ort: "Ebreichsdorf", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2484": { ort: "Weigelsdorf", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2485": { ort: "Wampersdorf", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },
  "2486": { ort: "Pottendorf", region: "Bruck an der Leitha", slug: "bruck-an-der-leitha" },

  // ── Wiener Neustadt ──
  "2700": { ort: "Wiener Neustadt", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2721": { ort: "Bad Fischau-Brunn", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2722": { ort: "Winzendorf-Muthmannsdorf", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2723": { ort: "Muthmannsdorf", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2724": { ort: "Hohe Wand", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2731": { ort: "St. Egyden am Steinfeld", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2732": { ort: "Würflach", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2733": { ort: "Grünbach am Schneeberg", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2751": { ort: "Matzendorf-Hölles", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2752": { ort: "Wöllersdorf-Steinabrückl", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2753": { ort: "Markt Piesting", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2754": { ort: "Waldegg", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2755": { ort: "Wiesmath", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2761": { ort: "Waidmannsfeld", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2762": { ort: "Ortmann", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2763": { ort: "Pernitz", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2770": { ort: "Gutenstein", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2801": { ort: "Katzelsdorf", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2802": { ort: "Hochwolkersdorf", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2803": { ort: "Schwarzenbach", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2804": { ort: "Lanzenkirchen", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2811": { ort: "Wiesmath", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2812": { ort: "Hollenthon", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2813": { ort: "Lichtenegg", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2821": { ort: "Lanzenkirchen", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2822": { ort: "Bad Erlach", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2823": { ort: "Pitten", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2824": { ort: "Seebenstein", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2831": { ort: "Scheiblingkirchen-Thernberg", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2832": { ort: "Thernberg", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2833": { ort: "Bromberg", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2840": { ort: "Grimmenstein", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2842": { ort: "Edlitz", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2843": { ort: "Thomasberg", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2844": { ort: "Kranichberg", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2851": { ort: "Krumbach", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2852": { ort: "Hochneukirchen-Gschaidt", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2853": { ort: "Bad Schönau", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2860": { ort: "Kirchschlag in der Buckligen Welt", region: "Wiener Neustadt", slug: "wiener-neustadt" },
  "2870": { ort: "Aspang-Markt", region: "Wiener Neustadt", slug: "wiener-neustadt" },

  // ── Mödling ──
  "2331": { ort: "Vösendorf", region: "Mödling", slug: "moedling" },
  "2332": { ort: "Hennersdorf", region: "Mödling", slug: "moedling" },
  "2333": { ort: "Leopoldsdorf bei Wien", region: "Mödling", slug: "moedling" },
  "2334": { ort: "Vösendorf", region: "Mödling", slug: "moedling" },
  "2335": { ort: "Leopoldsdorf", region: "Mödling", slug: "moedling" },
  "2344": { ort: "Maria Enzersdorf", region: "Mödling", slug: "moedling" },
  "2351": { ort: "Wiener Neudorf", region: "Mödling", slug: "moedling" },
  "2352": { ort: "Gumpoldskirchen", region: "Mödling", slug: "moedling" },
  "2353": { ort: "Guntramsdorf", region: "Mödling", slug: "moedling" },
  "2355": { ort: "Wiener Neudorf", region: "Mödling", slug: "moedling" },
  "2371": { ort: "Hinterbrühl", region: "Mödling", slug: "moedling" },
  "2372": { ort: "Gießhübl", region: "Mödling", slug: "moedling" },
  "2380": { ort: "Perchtoldsdorf", region: "Mödling", slug: "moedling" },
  "2381": { ort: "Laab im Walde", region: "Mödling", slug: "moedling" },
  "2382": { ort: "Breitenfurt bei Wien", region: "Mödling", slug: "moedling" },
  "2391": { ort: "Kaltenleutgeben", region: "Mödling", slug: "moedling" },
  "2392": { ort: "Sulz im Wienerwald", region: "Mödling", slug: "moedling" },

  // ── Neunkirchen ──
  "2620": { ort: "Neunkirchen", region: "Neunkirchen", slug: "neunkirchen" },
  "2624": { ort: "Breitenau", region: "Neunkirchen", slug: "neunkirchen" },
  "2625": { ort: "Schwarzau am Steinfeld", region: "Neunkirchen", slug: "neunkirchen" },
  "2626": { ort: "Wimpassing im Schwarzatale", region: "Neunkirchen", slug: "neunkirchen" },
  "2627": { ort: "Gleißenfeld", region: "Neunkirchen", slug: "neunkirchen" },
  "2630": { ort: "Ternitz", region: "Neunkirchen", slug: "neunkirchen" },
  "2631": { ort: "Stixenstein", region: "Neunkirchen", slug: "neunkirchen" },
  "2632": { ort: "Wimpassing an der Leitha", region: "Neunkirchen", slug: "neunkirchen" },
  "2640": { ort: "Gloggnitz", region: "Neunkirchen", slug: "neunkirchen" },
  "2641": { ort: "Schottwien", region: "Neunkirchen", slug: "neunkirchen" },
  "2642": { ort: "Göttschach", region: "Neunkirchen", slug: "neunkirchen" },
  "2643": { ort: "Payerbach", region: "Neunkirchen", slug: "neunkirchen" },
  "2650": { ort: "Payerbach", region: "Neunkirchen", slug: "neunkirchen" },
  "2651": { ort: "Reichenau an der Rax", region: "Neunkirchen", slug: "neunkirchen" },
  "2654": { ort: "Prein an der Rax", region: "Neunkirchen", slug: "neunkirchen" },
  "2661": { ort: "Raach am Hochgebirge", region: "Neunkirchen", slug: "neunkirchen" },
  "2662": { ort: "Schwarzau im Gebirge", region: "Neunkirchen", slug: "neunkirchen" },
  "2663": { ort: "Rohr im Gebirge", region: "Neunkirchen", slug: "neunkirchen" },
  "2671": { ort: "Otterthal", region: "Neunkirchen", slug: "neunkirchen" },
  "2672": { ort: "Feistritz am Wechsel", region: "Neunkirchen", slug: "neunkirchen" },
  "2673": { ort: "Breitenstein", region: "Neunkirchen", slug: "neunkirchen" },
  "2680": { ort: "Semmering", region: "Neunkirchen", slug: "neunkirchen" },
};

// ══════════════════════════════════════════════
// PLZ-Suche & Lookup Funktionen
// ══════════════════════════════════════════════

/** PLZ exakt nachschlagen */
function lookupPLZ(plz) {
  return PLZ_DATA[plz] || null;
}

/** PLZ oder Ort suchen (für Dropdown-Autocomplete) */
function searchPLZ(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase().trim();
  const isNumeric = /^\d/.test(q);

  if (isNumeric) {
    // PLZ-Suche: alle die mit der Eingabe beginnen
    return Object.entries(PLZ_DATA)
      .filter(([plz]) => plz.startsWith(q))
      .slice(0, 8)
      .map(([plz, data]) => ({ plz, ...data }));
  } else {
    // Ort-Suche: alle deren Ortsname die Eingabe enthält
    return Object.entries(PLZ_DATA)
      .filter(([, data]) => data.ort.toLowerCase().includes(q))
      .slice(0, 8)
      .map(([plz, data]) => ({ plz, ...data }));
  }
}

/** URL zur Bezirks-Landingpage */
function getLandingUrl(plzOrSlug) {
  const data = PLZ_DATA[plzOrSlug];
  const slug = data ? data.slug : plzOrSlug;
  return `region/${slug}.html`;
}
