/* =============================================
   REGION LANDING PAGE GENERATOR
   Erstellt dynamisch die Landing Page
   basierend auf ?region=slug Parameter
   ============================================= */

// Regionsdaten mit individuellen Texten
const REGION_CONTENT = {
  "graz": {
    name:        "Graz",
    title:       "Holzpellets lose kaufen in Graz",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose per Tankwagen direkt nach Graz und in die Grazer Umgebung.",
    tagline:     "Ihre Pellets-Lieferung für Graz & Umgebung",
    intro:       "Graz ist die Landeshauptstadt der Steiermark – und mit Steirer Pellets heizen Sie die Steirische Hauptstadt nachhaltig. Wir liefern lose Holzpellets direkt per Blasbefüllung zu Ihnen nach Hause oder in Ihren Betrieb.",
    highlight:   "Als einer der führenden Pellets-Produzenten der Steiermark beliefern wir Privathaushalte, Wohnhausanlagen und Gewerbebetriebe in ganz Graz – schnell, zuverlässig und zu fairen Preisen.",
    facts:       ["Alle Grazer Bezirke", "2–3 Tage Lieferzeit", "Ab 3 Tonnen lose", "Tankwagen Blasbefüllung"],
    plzList:     ["8010", "8020", "8036", "8041", "8042", "8043", "8044", "8045", "8046", "8047", "8051", "8052", "8053", "8054", "8055"],
  },
  "graz-umgebung": {
    name:        "Graz-Umgebung",
    title:       "Holzpellets lose in der Graz-Umgebung",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Feldkirchen, Hart bei Graz, Raaba und in die gesamte Graz-Umgebung.",
    tagline:     "Pellets-Lieferung für die Graz-Umgebung",
    intro:       "In der Graz-Umgebung – von Feldkirchen über Hart bis Hausmannstätten – liefern wir lose Holzpellets direkt per Tankwagen. Kurze Transportwege, frische Qualität, faire Preise.",
    highlight:   "Als regionaler Hersteller aus Köflach sind wir für die gesamte Graz-Umgebung schnell erreichbar. Wir kennen die Region und liefern zuverlässig.",
    facts:       ["Graz-Umgebung komplett", "2–4 Tage Lieferzeit", "Ab 3 Tonnen", "Direkt ab Hersteller"],
    plzList:     ["8061", "8062", "8063", "8071", "8072", "8073", "8074", "8075", "8076", "8081"],
  },
  "koeflach": {
    name:        "Köflach",
    title:       "Holzpellets lose kaufen in Köflach",
    description: "Steirer Pellets GmbH hat seinen Sitz in Köflach – hier liefern wir ENplus A1 Holzpellets direkt ab Werk.",
    tagline:     "Direkt vom Hersteller in Köflach",
    intro:       "Köflach ist unsere Heimat. Hier produzieren wir unsere ENplus A1 zertifizierten Holzpellets aus steirischen Sägespänen. Als Köflach-Kunde profitieren Sie von den kürzesten Lieferwegen und besten Preisen.",
    highlight:   "Pellets direkt ab Werk in Köflach – kein Zwischenhändler, volle Qualitätskontrolle, persönliche Beratung vor Ort.",
    facts:       ["Direkt ab Werk", "Sofortlieferung möglich", "Werksabholung möglich", "Beste Preise"],
    plzList:     ["8580", "8582", "8583"],
  },
  "voitsberg": {
    name:        "Voitsberg",
    title:       "Holzpellets lose in der Region Voitsberg",
    description: "Steirer Pellets beliefert den gesamten Bezirk Voitsberg mit losen ENplus A1 Holzpellets per Tankwagen.",
    tagline:     "Ihre Heimlieferung im Bezirk Voitsberg",
    intro:       "Der Bezirk Voitsberg ist unsere Heimregion. Von Voitsberg über Bärnbach bis Maria Lankowitz kennen wir jeden Winkel. Wir liefern Ihnen die besten Pellets direkt vor die Haustür.",
    highlight:   "Als lokaler Hersteller aus Köflach sind wir der natürliche Partner für alle Kunden im Bezirk Voitsberg. Kurze Wege, persönlicher Kontakt, Top-Qualität.",
    facts:       ["Heimlieferung im Bezirk", "1–2 Tage Lieferzeit", "Ab 3 Tonnen", "Persönliche Beratung"],
    plzList:     ["8570", "8572", "8573", "8580", "8582", "8583", "8591", "8592"],
  },
  "weiz": {
    name:        "Weiz",
    title:       "Holzpellets lose kaufen in Weiz",
    description: "Steirer Pellets liefert loose ENplus A1 Holzpellets in den Bezirk Weiz – von Weiz über Gleisdorf bis Birkfeld.",
    tagline:     "Pellets-Lieferung für den Bezirk Weiz",
    intro:       "Der Bezirk Weiz mit seinen Gemeinden Weiz, Gleisdorf, Birkfeld und Anger zählt zu unseren wichtigsten Liefergebieten. Wir kennen die Region und ihre Heizanforderungen.",
    highlight:   "Von Gleisdorf bis in die hügelige Landschaft rund um Weiz – wir kommen mit dem Tankwagen zu Ihnen und befüllen Ihren Pellettank schnell und sauber.",
    facts:       ["Bezirk Weiz komplett", "2–4 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8160", "8162", "8163", "8181", "8182", "8183", "8190", "8192"],
  },
  "leoben": {
    name:        "Leoben",
    title:       "Holzpellets lose kaufen in Leoben",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Leoben, Kapfenberg, Bruck an der Mur und in die Obersteiermark.",
    tagline:     "Pellets-Lieferung für die Region Leoben",
    intro:       "Die Industriestadt Leoben und die gesamte Obersteiermark werden von uns zuverlässig mit losen Holzpellets versorgt. Hohe Qualität trifft auf kurze Wege.",
    highlight:   "Für Betriebe und Haushalte in Leoben und Umgebung bieten wir besonders wirtschaftliche Konditionen bei Großmengen.",
    facts:       ["Leoben & Umgebung", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Großmengen-Rabatt"],
    plzList:     ["8700", "8712", "8713", "8770", "8790"],
  },
  "murtal": {
    name:        "Murtal",
    title:       "Holzpellets lose im Murtal",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in das gesamte Murtal – Knittelfeld, Judenburg, Zeltweg.",
    tagline:     "Ihre Pellets-Lieferung ins Murtal",
    intro:       "Das Murtal – mit Knittelfeld, Judenburg und Zeltweg – ist eine wichtige Lieferregion für uns. Wir bringen Ihre losen Pellets pünktlich und in höchster Qualität.",
    highlight:   "Egal ob privates Eigenheim oder Gewerbegebäude im Murtal: Wir liefern die passende Menge und beraten Sie gerne zur optimalen Tankgröße.",
    facts:       ["Ganzes Murtal", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Gewerbe & Privat"],
    plzList:     ["8720", "8721", "8724", "8725", "8750", "8753", "8755"],
  },
  "bruck-mur": {
    name:        "Bruck an der Mur",
    title:       "Holzpellets lose in Bruck an der Mur",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Bruck an der Mur und Kapfenberg.",
    tagline:     "Pellets-Lieferung für Bruck & Kapfenberg",
    intro:       "Bruck an der Mur und Kapfenberg sind wichtige Anlaufpunkte in unserer Lieferroute. Wir beliefern beide Städte sowie die umliegenden Gemeinden regelmäßig mit frischen, losen Pellets.",
    highlight:   "Qualitätspellets aus Köflach – direkt zu Ihnen nach Bruck oder Kapfenberg. Zuverlässig, sauber, ENplus A1 zertifiziert.",
    facts:       ["Bruck & Kapfenberg", "3–4 Tage Lieferzeit", "Ab 3 Tonnen", "Direkt ab Hersteller"],
    plzList:     ["8600", "8605"],
  },
  "muerzzuschlag": {
    name:        "Mürzzuschlag",
    title:       "Holzpellets lose in Mürzzuschlag",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Mürzzuschlag, Langenwang und in die Mürzregion.",
    tagline:     "Pellets-Lieferung für die Mürzregion",
    intro:       "Die Mürzregion mit Mürzzuschlag und Langenwang gehört zu unserem regulären Liefergebiet. Wir sorgen dafür, dass Ihr Pellettank vor dem Winter gefüllt ist.",
    highlight:   "Heizen Sie die Mürzregion nachhaltig mit unseren steirischen Holzpellets – direkt per Blasbefüllung in Ihren Keller.",
    facts:       ["Mürzregion", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8680", "8684", "8685"],
  },
  "leibnitz": {
    name:        "Leibnitz",
    title:       "Holzpellets lose im Bezirk Leibnitz",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Leibnitz – von Leibnitz über Gamlitz bis Ehrenhausen.",
    tagline:     "Pellets-Lieferung für den Bezirk Leibnitz",
    intro:       "Im Südwesten der Steiermark liefern wir unsere hochwertigen Holzpellets in den Bezirk Leibnitz. Von der Weinregion Gamlitz bis Wildon – wir kommen zu Ihnen.",
    highlight:   "Auch im sonnigen Süden der Steiermark wissen Pelletbesitzer unsere Qualität zu schätzen. Bestellen Sie rechtzeitig für die Heizsaison.",
    facts:       ["Bezirk Leibnitz", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Südsteiermark"],
    plzList:     ["8430", "8435", "8444", "8461", "8462", "8463"],
  },
  "deutschlandsberg": {
    name:        "Deutschlandsberg",
    title:       "Holzpellets lose in Deutschlandsberg",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Deutschlandsberg.",
    tagline:     "Pellets-Lieferung für Deutschlandsberg",
    intro:       "Der Bezirk Deutschlandsberg im Westen der Steiermark wird von uns regelmäßig mit hochwertigen, losen Holzpellets beliefert.",
    highlight:   "Vom Sausal bis Schwanberg – unsere Tankwagen kommen zu Ihnen und befüllen Ihren Pellettank komfortabel per Blasbefüllung.",
    facts:       ["Bezirk Deutschlandsberg", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8530", "8541", "8542", "8543"],
  },
  "hartberg": {
    name:        "Hartberg",
    title:       "Holzpellets lose in Hartberg",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Hartberg und in die Oststeiermark.",
    tagline:     "Pellets-Lieferung für Hartberg & Oststeiermark",
    intro:       "Hartberg und die Oststeiermark sind Teile unseres Liefergebiets. Wir bringen Ihnen frische, ENplus A1 zertifizierte Holzpellets direkt ins Haus.",
    highlight:   "Heizen Sie Ihren Haushalt in der Oststeiermark mit nachhaltigen, regionalen Pellets aus steirischen Sägespänen.",
    facts:       ["Bezirk Hartberg-Fürstenfeld", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "Oststeiermark"],
    plzList:     ["8230", "8250"],
  },
  "fuerstenfeld": {
    name:        "Fürstenfeld",
    title:       "Holzpellets lose in Fürstenfeld",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Fürstenfeld, Bad Waltersdorf und Bad Blumau.",
    tagline:     "Pellets-Lieferung für Fürstenfeld",
    intro:       "Die Thermenregion rund um Fürstenfeld und Bad Waltersdorf wird von uns mit hochwertigen Holzpellets versorgt. Nachhaltiges Heizen in der schönen Oststeiermark.",
    highlight:   "Von der Kurzentrum-Region bis hin zu privaten Haushalten – wir liefern Ihre losen Pellets pünktlich und zuverlässig.",
    facts:       ["Fürstenfeld & Thermenregion", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8280", "8282", "8283"],
  },
  "murau": {
    name:        "Murau",
    title:       "Holzpellets lose in Murau",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Murau und in die obere Steiermark.",
    tagline:     "Pellets-Lieferung für den Bezirk Murau",
    intro:       "Der waldreiche Bezirk Murau ist eine Region, in der Pelletheizungen besonders verbreitet sind. Als steirischer Hersteller sind wir Ihr idealer Partner.",
    highlight:   "In einer Holzregion wie Murau wissen Hausbesitzer die Qualität regionaler Holzpellets zu schätzen. Wir kommen zu Ihnen.",
    facts:       ["Bezirk Murau", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "Holzregion"],
    plzList:     ["8850", "8851", "8852", "8861", "8862"],
  },
  "liezen": {
    name:        "Liezen",
    title:       "Holzpellets lose im Ennstal & Liezen",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in das Ennstal, nach Liezen, Schladming und Bad Aussee.",
    tagline:     "Pellets-Lieferung für das Ennstal",
    intro:       "Das Ennstal mit Liezen, Schladming und Bad Aussee ist eine schneereiche Region – perfekt für effiziente Pelletheizungen. Wir beliefern die gesamte Region mit losen Pellets.",
    highlight:   "Für Hotels, Pensionen und Privathäuser im Ennstal bieten wir maßgeschneiderte Lieferlösungen – auch für große Mengen.",
    facts:       ["Ennstal & Ausseerland", "4–6 Tage Lieferzeit", "Ab 3 Tonnen", "Tourismusregion"],
    plzList:     ["8940", "8950", "8960", "8970", "8971", "8990"],
  },
  "suedoststeiermark": {
    name:        "Südoststeiermark",
    title:       "Holzpellets lose in der Südoststeiermark",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in die Südoststeiermark – Feldbach, Riegersburg, Bad Radkersburg.",
    tagline:     "Pellets-Lieferung für die Südoststeiermark",
    intro:       "Von Feldbach über Riegersburg bis Bad Radkersburg an der slowenischen Grenze beliefern wir die Südoststeiermark mit hochwertigen, losen Holzpellets.",
    highlight:   "Die hügelige Südoststeiermark schätzt nachhaltige Energie. Unsere Pellets aus steirischen Sägespänen sind die ideale Heizlösung.",
    facts:       ["Südoststeiermark", "4–6 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8330", "8333", "8490", "8492", "8493"],
  },
  "kaernten": {
    name:        "Kärnten",
    title:       "Holzpellets lose in Kärnten",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose auch nach Kärnten – Klagenfurt und Umgebung.",
    tagline:     "Pellets-Lieferung nach Kärnten",
    intro:       "Auch Kärnten gehört zu unserem Liefergebiet. Wir beliefern Klagenfurt und die Kärntner Umgebung auf Anfrage mit unseren hochwertigen losen Holzpellets.",
    highlight:   "Für Kärntner Kunden empfehlen wir, frühzeitig zu bestellen. Bitte kontaktieren Sie uns für individuelle Angebote.",
    facts:       ["Kärnten auf Anfrage", "5–7 Tage Lieferzeit", "Ab 5 Tonnen", "Mindermenge Aufschlag"],
    plzList:     ["9020", "9021", "9100"],
  },
  "wien": {
    name:        "Wien",
    title:       "Holzpellets lose in Wien",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose auch nach Wien – auf Anfrage für größere Mengen.",
    tagline:     "Pellets-Lieferung nach Wien",
    intro:       "Wien ist als Bundeshauptstadt kein typisches Liefergebiet für uns – aber für größere Abnehmer und Gewerbebetriebe liefern wir gerne nach Wien.",
    highlight:   "Für Wien bitten wir um telefonische Voranmeldung. Wir erstellen Ihnen ein individuelles Angebot inklusive Transportkosten.",
    facts:       ["Wien auf Anfrage", "5–7 Tage Lieferzeit", "Ab 10 Tonnen", "Bitte anrufen"],
    plzList:     ["1010", "1020", "1030", "1100", "1110", "1120", "1130", "1140", "1150", "1160", "1170", "1180", "1190", "1200", "1210", "1220", "1230"],
  },
  "niederoesterreich": {
    name:        "Niederösterreich",
    title:       "Holzpellets lose in Niederösterreich",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Niederösterreich – St. Pölten, Wiener Neustadt – auf Anfrage.",
    tagline:     "Pellets-Lieferung nach Niederösterreich",
    intro:       "Für Kunden in Niederösterreich liefern wir auf Anfrage. Bitte kontaktieren Sie uns direkt für ein individuelles Angebot.",
    highlight:   "Wir freuen uns über jeden Kunden – auch außerhalb der Steiermark. Rufen Sie uns an und wir finden gemeinsam eine Lösung.",
    facts:       ["NÖ auf Anfrage", "6–8 Tage Lieferzeit", "Ab 10 Tonnen", "Bitte anrufen"],
    plzList:     ["3100", "2700"],
  },
};
