/* =============================================
   REGION LANDING PAGE GENERATOR
   Erstellt dynamisch die Landing Page
   basierend auf ?region=slug Parameter
   ============================================= */

// Regionsdaten mit individuellen Texten
const REGION_CONTENT = {
  "graz": {
    name:        "Graz",
    title:       "Holzpellets lose kaufen in Graz",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose per Tankwagen direkt nach Graz und in die Grazer Umgebung.",
    tagline:     "Lose Pellets für Graz und die Grazer Umgebung",
    intro:       "Wenn Sie Holzpellets lose in Graz kaufen möchten, liefert Steirer Pellets direkt per Tankwagen zu Ihrem Haus, Mehrparteienobjekt oder Betrieb. Wir beliefern alle Grazer Bezirke mit ENplus A1 Pellets und sauberer Blasbefüllung.",
    highlight:   "Von Eggenberg bis St. Peter profitieren Grazer Kundinnen und Kunden von einer regionalen Lieferung aus der Steiermark, planbaren Lieferwochen und persönlicher Betreuung.",
    facts:       ["Alle Grazer Bezirke", "2–3 Tage Lieferzeit", "Ab 3 Tonnen lose", "Tankwagen Blasbefüllung"],
    plzList:     ["8010", "8020", "8036", "8041", "8042", "8043", "8044", "8045", "8046", "8047", "8051", "8052", "8053", "8054", "8055"],
  },
  "graz-umgebung": {
    name:        "Graz-Umgebung",
    title:       "Holzpellets lose in der Graz-Umgebung",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Feldkirchen, Hart bei Graz, Raaba und in die gesamte Graz-Umgebung.",
    tagline:     "Lose Pellets für die Graz-Umgebung",
    intro:       "Wer Holzpellets lose in der Graz-Umgebung kaufen will, braucht eine Lieferung, die pünktlich und unkompliziert funktioniert. Genau dafür beliefern wir Orte wie Feldkirchen, Hart bei Graz, Raaba und viele weitere Gemeinden direkt per Tankwagen.",
    highlight:   "Die Nähe zu unserem Standort in Köflach hilft bei kurzen Wegen, guter Erreichbarkeit und einer Lieferung, die für viele Haushalte in der Graz-Umgebung besonders praktisch ist.",
    facts:       ["Graz-Umgebung komplett", "2–4 Tage Lieferzeit", "Ab 3 Tonnen", "Direkt ab Hersteller"],
    plzList:     ["8061", "8062", "8063", "8071", "8072", "8073", "8074", "8075", "8076", "8081"],
  },
  "koeflach": {
    name:        "Köflach",
    title:       "Holzpellets lose kaufen in Köflach",
    description: "Steirer Pellets GmbH hat seinen Sitz in Köflach – hier liefern wir ENplus A1 Holzpellets direkt ab Werk.",
    tagline:     "Direkt vom Hersteller in Köflach",
    intro:       "In Köflach ist Steirer Pellets zu Hause. Wenn Sie hier Holzpellets lose kaufen, kommen die Pellets direkt vom Hersteller und werden ohne Umwege zu Ihnen geliefert oder nach Absprache ab Werk bereitgestellt.",
    highlight:   "Gerade in Köflach sind kurze Wege, persönlicher Kontakt und direkte Abstimmung mit dem Produzenten ein klarer Vorteil für Haushalte und Betriebe.",
    facts:       ["Direkt ab Werk", "Sofortlieferung möglich", "Werksabholung möglich", "Beste Preise"],
    plzList:     ["8580", "8582", "8583"],
  },
  "voitsberg": {
    name:        "Voitsberg",
    title:       "Holzpellets lose in der Region Voitsberg",
    description: "Steirer Pellets beliefert den gesamten Bezirk Voitsberg mit losen ENplus A1 Holzpellets per Tankwagen.",
    tagline:     "Lose Pellets für den Bezirk Voitsberg",
    intro:       "Im Bezirk Voitsberg liefern wir lose Holzpellets dorthin, wo sie gebraucht werden: nach Voitsberg, Bärnbach, Maria Lankowitz und in die umliegenden Gemeinden. Die Region kennen wir aus dem Alltag, nicht nur von der Karte.",
    highlight:   "Als Hersteller aus Köflach sind wir in unserer Heimregion besonders nah dran. Das macht Abstimmung, Lieferung und Service für viele Kundinnen und Kunden im Bezirk Voitsberg einfacher.",
    facts:       ["Heimlieferung im Bezirk", "1–2 Tage Lieferzeit", "Ab 3 Tonnen", "Persönliche Beratung"],
    plzList:     ["8570", "8572", "8573", "8580", "8582", "8583", "8591", "8592"],
  },
  "weiz": {
    name:        "Weiz",
    title:       "Holzpellets lose kaufen in Weiz",
    description: "Steirer Pellets liefert lose ENplus A1 Holzpellets in den Bezirk Weiz – von Weiz über Gleisdorf bis Birkfeld.",
    tagline:     "Lose Pellets für den Bezirk Weiz",
    intro:       "Wenn Sie Holzpellets lose in Weiz, Gleisdorf, Birkfeld oder Anger kaufen möchten, liefern wir die passende Menge direkt per Blasbefüllung in Ihren Lagerraum oder Pellettank. So bleibt die Bestellung für viele Haushalte im Bezirk Weiz einfach planbar.",
    highlight:   "Im Bezirk Weiz zählen zuverlässige Lieferzeiten, saubere Befüllung und regionale Qualität. Genau darauf ist unsere Lieferung mit dem Tankwagen ausgerichtet.",
    facts:       ["Bezirk Weiz komplett", "2–4 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8160", "8162", "8163", "8181", "8182", "8183", "8190", "8192"],
  },
  "leoben": {
    name:        "Leoben",
    title:       "Holzpellets lose kaufen in Leoben",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Leoben, Kapfenberg, Bruck an der Mur und in die Obersteiermark.",
    tagline:     "Lose Pellets für Leoben und die Obersteiermark",
    intro:       "Steirer Pellets liefert lose Holzpellets nach Leoben, Kapfenberg, Bruck an der Mur und in weitere Teile der Obersteiermark. Damit können private Haushalte ebenso wie größere Abnehmer regional produzierte ENplus A1 Pellets beziehen.",
    highlight:   "Gerade in Leoben und Umgebung ist eine verlässliche Lieferung für Einfamilienhäuser, Mehrparteienobjekte und Betriebe wichtig. Wir planen Lieferwochen nachvollziehbar und beraten auch bei größeren Mengen.",
    facts:       ["Leoben & Umgebung", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Großmengen-Rabatt"],
    plzList:     ["8700", "8712", "8713", "8770", "8790"],
  },
  "murtal": {
    name:        "Murtal",
    title:       "Holzpellets lose im Murtal",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in das gesamte Murtal – Knittelfeld, Judenburg, Zeltweg.",
    tagline:     "Lose Pellets für das Murtal",
    intro:       "Im Murtal beliefern wir Haushalte und Betriebe in Knittelfeld, Judenburg, Zeltweg und den umliegenden Gemeinden mit losen Holzpellets. Die Lieferung erfolgt per Tankwagen direkt in den Pellettank oder Lagerraum.",
    highlight:   "Wer im Murtal Holzpellets kaufen will, achtet meist auf Zuverlässigkeit vor der Heizsaison. Mit regionaler Produktion, persönlicher Abstimmung und planbaren Lieferwochen sind wir dafür gut aufgestellt.",
    facts:       ["Ganzes Murtal", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Gewerbe & Privat"],
    plzList:     ["8720", "8721", "8724", "8725", "8750", "8753", "8755"],
  },
  "bruck-mur": {
    name:        "Bruck an der Mur",
    title:       "Holzpellets lose in Bruck an der Mur",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Bruck an der Mur und Kapfenberg.",
    tagline:     "Lose Pellets für Bruck und Kapfenberg",
    intro:       "Wenn Sie Holzpellets lose in Bruck an der Mur oder Kapfenberg kaufen möchten, liefern wir regelmäßig in die Region. Die Pellets kommen per Tankwagen direkt in Ihren Pellettank - sauber und ohne Sackware.",
    highlight:   "Für viele Haushalte zwischen Bruck und Kapfenberg zählen regionale Herkunft, ENplus A1 Qualität und eine unkomplizierte Lieferung. Genau darauf ist unser Angebot ausgerichtet.",
    facts:       ["Bruck & Kapfenberg", "3–4 Tage Lieferzeit", "Ab 3 Tonnen", "Direkt ab Hersteller"],
    plzList:     ["8600", "8605"],
  },
  "muerzzuschlag": {
    name:        "Mürzzuschlag",
    title:       "Holzpellets lose in Mürzzuschlag",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Mürzzuschlag, Langenwang und in die Mürzregion.",
    tagline:     "Lose Pellets für die Mürzregion",
    intro:       "In Mürzzuschlag, Langenwang und der umliegenden Mürzregion liefern wir lose Holzpellets direkt per Tankwagen. Gerade in kühleren Lagen ist es für viele Haushalte wichtig, die Heizsaison rechtzeitig einzuplanen.",
    highlight:   "Mit regional produzierten ENplus A1 Pellets und persönlich abgestimmten Lieferwochen unterstützen wir Kundinnen und Kunden in der Mürzregion bei einer verlässlichen Vorratshaltung.",
    facts:       ["Mürzregion", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8680", "8684", "8685"],
  },
  "leibnitz": {
    name:        "Leibnitz",
    title:       "Holzpellets lose im Bezirk Leibnitz",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Leibnitz – von Leibnitz über Gamlitz bis Ehrenhausen.",
    tagline:     "Lose Pellets für den Bezirk Leibnitz",
    intro:       "Im Bezirk Leibnitz liefern wir lose Holzpellets nach Leibnitz, Gamlitz, Ehrenhausen und in viele weitere Orte der Südsteiermark. Die Lieferung erfolgt direkt per Blasbefüllung und passt damit gut zu privaten Lagerräumen und Pellettanks.",
    highlight:   "Auch in der Südsteiermark sind kurze Wege, persönliche Beratung und eine rechtzeitige Bestellung vor der Heizsaison wichtige Gründe für einen regionalen Anbieter.",
    facts:       ["Bezirk Leibnitz", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Südsteiermark"],
    plzList:     ["8430", "8435", "8444", "8461", "8462", "8463"],
  },
  "deutschlandsberg": {
    name:        "Deutschlandsberg",
    title:       "Holzpellets lose in Deutschlandsberg",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Deutschlandsberg.",
    tagline:     "Lose Pellets für Deutschlandsberg",
    intro:       "Wer Holzpellets lose in Deutschlandsberg kaufen möchte, bekommt bei Steirer Pellets eine regionale Lieferung direkt per Tankwagen. Wir beliefern den Bezirk regelmäßig und kennen viele Zufahrten und Anforderungen vor Ort bereits aus der Praxis.",
    highlight:   "Von Deutschlandsberg bis Richtung Schwanberg profitieren Kundinnen und Kunden von ENplus A1 Qualität, sauberer Blasbefüllung und einer Lieferung ohne Umwege über Zwischenhändler.",
    facts:       ["Bezirk Deutschlandsberg", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8530", "8541", "8542", "8543"],
  },
  "hartberg": {
    name:        "Hartberg",
    title:       "Holzpellets lose in Hartberg",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Hartberg und in die Oststeiermark.",
    tagline:     "Lose Pellets für Hartberg und die Oststeiermark",
    intro:       "In Hartberg und der Oststeiermark liefern wir lose Holzpellets für Einfamilienhäuser, landwirtschaftliche Betriebe und weitere Gebäude mit Pelletheizung. Die Befüllung erfolgt direkt per Tankwagen und spart das Hantieren mit Säcken.",
    highlight:   "Für viele Kundinnen und Kunden in Hartberg zählen regionale Herkunft, planbare Lieferungen und eine Heizung, die weniger von Öl und Gas abhängig ist. Pellets sind dafür oft eine passende Lösung.",
    facts:       ["Bezirk Hartberg-Fürstenfeld", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "Oststeiermark"],
    plzList:     ["8230", "8250"],
  },
  "fuerstenfeld": {
    name:        "Fürstenfeld",
    title:       "Holzpellets lose in Fürstenfeld",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Fürstenfeld, Bad Waltersdorf und Bad Blumau.",
    tagline:     "Lose Pellets für Fürstenfeld",
    intro:       "Wenn Sie Holzpellets lose in Fürstenfeld, Bad Waltersdorf oder Bad Blumau kaufen möchten, liefern wir die gewünschte Menge direkt in Ihren Pellettank. So bleibt die Versorgung auch in der Heizsaison gut planbar.",
    highlight:   "In der Thermenregion sind für viele Haushalte eine saubere Lieferung, regionale Qualität und persönliche Erreichbarkeit besonders wichtig. Genau darauf legen wir bei jeder Lieferung Wert.",
    facts:       ["Fürstenfeld & Thermenregion", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8280", "8282", "8283"],
  },
  "murau": {
    name:        "Murau",
    title:       "Holzpellets lose in Murau",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Murau und in die obere Steiermark.",
    tagline:     "Lose Pellets für den Bezirk Murau",
    intro:       "Im Bezirk Murau ist Heizen mit Holz vielerorts vertraut. Wir liefern lose Holzpellets direkt in die Region und verbinden regionale Produktion mit einer praktischen Tankwagen-Lieferung für Haushalte und Betriebe.",
    highlight:   "Gerade in einer Holzregion wie Murau passen Pellets gut zu dem Wunsch nach erneuerbarer Wärme, kurzen Wegen und stärkerer Wertschöpfung in der Region.",
    facts:       ["Bezirk Murau", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "Holzregion"],
    plzList:     ["8850", "8851", "8852", "8861", "8862"],
  },
  "liezen": {
    name:        "Liezen",
    title:       "Holzpellets lose im Ennstal & Liezen",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in das Ennstal, nach Liezen, Schladming und Bad Aussee.",
    tagline:     "Lose Pellets für Liezen und das Ennstal",
    intro:       "In Liezen, Schladming, Bad Aussee und weiteren Orten im Ennstal liefern wir lose Holzpellets direkt per Tankwagen. Gerade in Regionen mit längerer Heizperiode spielt eine verlässliche Vorratsplanung eine große Rolle.",
    highlight:   "Ob Privathaus, Pension oder größeres Objekt: Im Ennstal kommt es auf passende Mengen, saubere Befüllung und gut abgestimmte Liefertermine an. Genau dabei unterstützen wir.",
    facts:       ["Ennstal & Ausseerland", "4–6 Tage Lieferzeit", "Ab 3 Tonnen", "Tourismusregion"],
    plzList:     ["8940", "8950", "8960", "8970", "8971", "8990"],
  },
  "suedoststeiermark": {
    name:        "Südoststeiermark",
    title:       "Holzpellets lose in der Südoststeiermark",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in die Südoststeiermark – Feldbach, Riegersburg, Bad Radkersburg.",
    tagline:     "Lose Pellets für die Südoststeiermark",
    intro:       "Von Feldbach über Riegersburg bis Bad Radkersburg liefern wir lose Holzpellets in die Südoststeiermark. Die Lieferung erfolgt direkt per Tankwagen und ist für viele Haushalte eine bequeme Alternative zum Nachfüllen von Sackware.",
    highlight:   "In der Südoststeiermark spielen regionale Herkunft, persönlicher Service und eine planbare Heizsaison für viele Kundinnen und Kunden eine wichtige Rolle. Daran orientiert sich auch unsere Lieferung.",
    facts:       ["Südoststeiermark", "4–6 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8330", "8333", "8490", "8492", "8493"],
  },
  "kaernten": {
    name:        "Kärnten",
    title:       "Holzpellets lose in Kärnten",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose auch nach Kärnten – Klagenfurt und Umgebung.",
    tagline:     "Lose Pellets nach Kärnten auf Anfrage",
    intro:       "Auch nach Kärnten liefern wir lose Holzpellets auf Anfrage, vor allem im Raum Klagenfurt und Völkermarkt. Weil die Wege länger sind als in unserem Kerngebiet, stimmen wir Menge und Termin immer individuell ab.",
    highlight:   "Für Kundinnen und Kunden in Kärnten lohnt sich eine frühzeitige Anfrage. So können wir Verfügbarkeit, Lieferroute und passende Menge sauber einplanen.",
    facts:       ["Kärnten auf Anfrage", "5–7 Tage Lieferzeit", "Ab 5 Tonnen", "Mindermenge Aufschlag"],
    plzList:     ["9020", "9021", "9100"],
  },
  "wien": {
    name:        "Wien",
    title:       "Holzpellets lose in Wien",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose auch nach Wien – auf Anfrage für größere Mengen.",
    tagline:     "Lose Pellets nach Wien auf Anfrage",
    intro:       "Wien gehört nicht zu unserem klassischen Kerngebiet, dennoch liefern wir lose Holzpellets auf Anfrage für größere Mengen und passende Rahmenbedingungen. Dabei prüfen wir Lieferung und Transport individuell.",
    highlight:   "Wenn Sie in Wien Pellets kaufen möchten, ist ein kurzer Anruf am sinnvollsten. Dann klären wir direkt, ob Menge, Zufahrt und Lieferroute gut zusammenpassen.",
    facts:       ["Wien auf Anfrage", "5–7 Tage Lieferzeit", "Ab 10 Tonnen", "Bitte anrufen"],
    plzList:     ["1010", "1020", "1030", "1100", "1110", "1120", "1130", "1140", "1150", "1160", "1170", "1180", "1190", "1200", "1210", "1220", "1230"],
  },
  "niederoesterreich": {
    name:        "Niederösterreich",
    title:       "Holzpellets lose in Niederösterreich",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Niederösterreich – St. Pölten, Wiener Neustadt – auf Anfrage.",
    tagline:     "Lose Pellets nach Niederösterreich auf Anfrage",
    intro:       "Nach Niederösterreich liefern wir lose Holzpellets auf Anfrage, etwa in Richtung St. Pölten oder Wiener Neustadt. Weil diese Orte außerhalb unseres regulären Kerngebiets liegen, stimmen wir jede Lieferung individuell ab.",
    highlight:   "Ein kurzer telefonischer Kontakt ist hier der beste Weg. So lässt sich schnell klären, welche Menge sinnvoll ist und ob die Lieferung in Ihr Gebiet gut planbar ist.",
    facts:       ["NÖ auf Anfrage", "6–8 Tage Lieferzeit", "Ab 10 Tonnen", "Bitte anrufen"],
    plzList:     ["3100", "2700"],
  },
};
