/* =============================================
   REGION LANDING PAGE GENERATOR
   Erstellt dynamisch die Landing Page
   basierend auf ?region=slug Parameter
   ============================================= */

// Regionsdaten mit individuellen Texten
const REGION_CONTENT = {
  "graz": {
    name:        "Graz",
    title:       "Holzpellets lose kaufen in Graz",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose per Tankwagen direkt nach Graz und in die Grazer Umgebung.",
    tagline:     "Lose Pellets fuer Graz und die Grazer Umgebung",
    intro:       "Wenn Sie Holzpellets lose in Graz kaufen moechten, liefert Steirer Pellets direkt per Tankwagen zu Ihrem Haus, Mehrparteienobjekt oder Betrieb. Wir beliefern alle Grazer Bezirke mit ENplus A1 Pellets und sauberer Blasbefuellung.",
    highlight:   "Von Eggenberg bis St. Peter profitieren Grazer Kundinnen und Kunden von einer regionalen Lieferung aus der Steiermark, planbaren Lieferwochen und persoenlicher Betreuung.",
    facts:       ["Alle Grazer Bezirke", "2–3 Tage Lieferzeit", "Ab 3 Tonnen lose", "Tankwagen Blasbefüllung"],
    plzList:     ["8010", "8020", "8036", "8041", "8042", "8043", "8044", "8045", "8046", "8047", "8051", "8052", "8053", "8054", "8055"],
  },
  "graz-umgebung": {
    name:        "Graz-Umgebung",
    title:       "Holzpellets lose in der Graz-Umgebung",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Feldkirchen, Hart bei Graz, Raaba und in die gesamte Graz-Umgebung.",
    tagline:     "Lose Pellets fuer die Graz-Umgebung",
    intro:       "Wer Holzpellets lose in der Graz-Umgebung kaufen will, braucht eine Lieferung, die puenktlich und unkompliziert funktioniert. Genau dafuer beliefern wir Orte wie Feldkirchen, Hart bei Graz, Raaba und viele weitere Gemeinden direkt per Tankwagen.",
    highlight:   "Die Naehe zu unserem Standort in Koeflach hilft bei kurzen Wegen, guter Erreichbarkeit und einer Lieferung, die fuer viele Haushalte in der Graz-Umgebung besonders praktisch ist.",
    facts:       ["Graz-Umgebung komplett", "2–4 Tage Lieferzeit", "Ab 3 Tonnen", "Direkt ab Hersteller"],
    plzList:     ["8061", "8062", "8063", "8071", "8072", "8073", "8074", "8075", "8076", "8081"],
  },
  "koeflach": {
    name:        "Köflach",
    title:       "Holzpellets lose kaufen in Köflach",
    description: "Steirer Pellets GmbH hat seinen Sitz in Köflach – hier liefern wir ENplus A1 Holzpellets direkt ab Werk.",
    tagline:     "Direkt vom Hersteller in Koeflach",
    intro:       "In Koeflach ist Steirer Pellets zu Hause. Wenn Sie hier Holzpellets lose kaufen, kommen die Pellets direkt vom Hersteller und werden ohne Umwege zu Ihnen geliefert oder nach Absprache ab Werk bereitgestellt.",
    highlight:   "Gerade in Koeflach sind kurze Wege, persoenlicher Kontakt und direkte Abstimmung mit dem Produzenten ein klarer Vorteil fuer Haushalte und Betriebe.",
    facts:       ["Direkt ab Werk", "Sofortlieferung möglich", "Werksabholung möglich", "Beste Preise"],
    plzList:     ["8580", "8582", "8583"],
  },
  "voitsberg": {
    name:        "Voitsberg",
    title:       "Holzpellets lose in der Region Voitsberg",
    description: "Steirer Pellets beliefert den gesamten Bezirk Voitsberg mit losen ENplus A1 Holzpellets per Tankwagen.",
    tagline:     "Lose Pellets fuer den Bezirk Voitsberg",
    intro:       "Im Bezirk Voitsberg liefern wir lose Holzpellets dorthin, wo sie gebraucht werden: nach Voitsberg, Baernbach, Maria Lankowitz und in die umliegenden Gemeinden. Die Region kennen wir aus dem Alltag, nicht nur von der Karte.",
    highlight:   "Als Hersteller aus Koeflach sind wir in unserer Heimregion besonders nah dran. Das macht Abstimmung, Lieferung und Service fuer viele Kundinnen und Kunden im Bezirk Voitsberg einfacher.",
    facts:       ["Heimlieferung im Bezirk", "1–2 Tage Lieferzeit", "Ab 3 Tonnen", "Persönliche Beratung"],
    plzList:     ["8570", "8572", "8573", "8580", "8582", "8583", "8591", "8592"],
  },
  "weiz": {
    name:        "Weiz",
    title:       "Holzpellets lose kaufen in Weiz",
    description: "Steirer Pellets liefert lose ENplus A1 Holzpellets in den Bezirk Weiz – von Weiz über Gleisdorf bis Birkfeld.",
    tagline:     "Lose Pellets fuer den Bezirk Weiz",
    intro:       "Wenn Sie Holzpellets lose in Weiz, Gleisdorf, Birkfeld oder Anger kaufen moechten, liefern wir die passende Menge direkt per Blasbefuellung in Ihren Lagerraum oder Pellettank. So bleibt die Bestellung fuer viele Haushalte im Bezirk Weiz einfach planbar.",
    highlight:   "Im Bezirk Weiz zaehlen zuverlaessige Lieferzeiten, saubere Befuellung und regionale Qualitaet. Genau darauf ist unsere Lieferung mit dem Tankwagen ausgerichtet.",
    facts:       ["Bezirk Weiz komplett", "2–4 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8160", "8162", "8163", "8181", "8182", "8183", "8190", "8192"],
  },
  "leoben": {
    name:        "Leoben",
    title:       "Holzpellets lose kaufen in Leoben",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Leoben, Kapfenberg, Bruck an der Mur und in die Obersteiermark.",
    tagline:     "Lose Pellets fuer Leoben und die Obersteiermark",
    intro:       "Steirer Pellets liefert lose Holzpellets nach Leoben, Kapfenberg, Bruck an der Mur und in weitere Teile der Obersteiermark. Damit koennen private Haushalte ebenso wie groessere Abnehmer regional produzierte ENplus A1 Pellets beziehen.",
    highlight:   "Gerade in Leoben und Umgebung ist eine verlaessliche Lieferung fuer Einfamilienhaeuser, Mehrparteienobjekte und Betriebe wichtig. Wir planen Lieferwochen nachvollziehbar und beraten auch bei groesseren Mengen.",
    facts:       ["Leoben & Umgebung", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Großmengen-Rabatt"],
    plzList:     ["8700", "8712", "8713", "8770", "8790"],
  },
  "murtal": {
    name:        "Murtal",
    title:       "Holzpellets lose im Murtal",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in das gesamte Murtal – Knittelfeld, Judenburg, Zeltweg.",
    tagline:     "Lose Pellets fuer das Murtal",
    intro:       "Im Murtal beliefern wir Haushalte und Betriebe in Knittelfeld, Judenburg, Zeltweg und den umliegenden Gemeinden mit losen Holzpellets. Die Lieferung erfolgt per Tankwagen direkt in den Pellettank oder Lagerraum.",
    highlight:   "Wer im Murtal Holzpellets kaufen will, achtet meist auf Zuverlaessigkeit vor der Heizsaison. Mit regionaler Produktion, persoenlicher Abstimmung und planbaren Lieferwochen sind wir dafuer gut aufgestellt.",
    facts:       ["Ganzes Murtal", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Gewerbe & Privat"],
    plzList:     ["8720", "8721", "8724", "8725", "8750", "8753", "8755"],
  },
  "bruck-mur": {
    name:        "Bruck an der Mur",
    title:       "Holzpellets lose in Bruck an der Mur",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Bruck an der Mur und Kapfenberg.",
    tagline:     "Lose Pellets fuer Bruck und Kapfenberg",
    intro:       "Wenn Sie Holzpellets lose in Bruck an der Mur oder Kapfenberg kaufen moechten, liefern wir regelmaessig in die Region. Die Pellets kommen per Tankwagen direkt in Ihren Pellettank - sauber und ohne Sackware.",
    highlight:   "Fuer viele Haushalte zwischen Bruck und Kapfenberg zaehlen regionale Herkunft, ENplus A1 Qualitaet und eine unkomplizierte Lieferung. Genau darauf ist unser Angebot ausgerichtet.",
    facts:       ["Bruck & Kapfenberg", "3–4 Tage Lieferzeit", "Ab 3 Tonnen", "Direkt ab Hersteller"],
    plzList:     ["8600", "8605"],
  },
  "muerzzuschlag": {
    name:        "Mürzzuschlag",
    title:       "Holzpellets lose in Mürzzuschlag",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Mürzzuschlag, Langenwang und in die Mürzregion.",
    tagline:     "Lose Pellets fuer die Muerzregion",
    intro:       "In Muerzzuschlag, Langenwang und der umliegenden Muerzregion liefern wir lose Holzpellets direkt per Tankwagen. Gerade in kuehleren Lagen ist es fuer viele Haushalte wichtig, die Heizsaison rechtzeitig einzuplanen.",
    highlight:   "Mit regional produzierten ENplus A1 Pellets und persoenlich abgestimmten Lieferwochen unterstuetzen wir Kundinnen und Kunden in der Muerzregion bei einer verlaesslichen Vorratshaltung.",
    facts:       ["Mürzregion", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8680", "8684", "8685"],
  },
  "leibnitz": {
    name:        "Leibnitz",
    title:       "Holzpellets lose im Bezirk Leibnitz",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Leibnitz – von Leibnitz über Gamlitz bis Ehrenhausen.",
    tagline:     "Lose Pellets fuer den Bezirk Leibnitz",
    intro:       "Im Bezirk Leibnitz liefern wir lose Holzpellets nach Leibnitz, Gamlitz, Ehrenhausen und in viele weitere Orte der Suedsteiermark. Die Lieferung erfolgt direkt per Blasbefuellung und passt damit gut zu privaten Lagerraeumen und Pellettanks.",
    highlight:   "Auch in der Suedsteiermark sind kurze Wege, persoenliche Beratung und eine rechtzeitige Bestellung vor der Heizsaison wichtige Gruende fuer einen regionalen Anbieter.",
    facts:       ["Bezirk Leibnitz", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "Südsteiermark"],
    plzList:     ["8430", "8435", "8444", "8461", "8462", "8463"],
  },
  "deutschlandsberg": {
    name:        "Deutschlandsberg",
    title:       "Holzpellets lose in Deutschlandsberg",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Deutschlandsberg.",
    tagline:     "Lose Pellets fuer Deutschlandsberg",
    intro:       "Wer Holzpellets lose in Deutschlandsberg kaufen moechte, bekommt bei Steirer Pellets eine regionale Lieferung direkt per Tankwagen. Wir beliefern den Bezirk regelmaessig und kennen viele Zufahrten und Anforderungen vor Ort bereits aus der Praxis.",
    highlight:   "Von Deutschlandsberg bis Richtung Schwanberg profitieren Kundinnen und Kunden von ENplus A1 Qualitaet, sauberer Blasbefuellung und einer Lieferung ohne Umwege ueber Zwischenhaendler.",
    facts:       ["Bezirk Deutschlandsberg", "3–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8530", "8541", "8542", "8543"],
  },
  "hartberg": {
    name:        "Hartberg",
    title:       "Holzpellets lose in Hartberg",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Hartberg und in die Oststeiermark.",
    tagline:     "Lose Pellets fuer Hartberg und die Oststeiermark",
    intro:       "In Hartberg und der Oststeiermark liefern wir lose Holzpellets fuer Einfamilienhaeuser, landwirtschaftliche Betriebe und weitere Gebaeude mit Pelletheizung. Die Befuellung erfolgt direkt per Tankwagen und spart das Hantieren mit Saecken.",
    highlight:   "Fuer viele Kundinnen und Kunden in Hartberg zaehlen regionale Herkunft, planbare Lieferungen und eine Heizung, die weniger von Oel und Gas abhaengig ist. Pellets sind dafuer oft eine passende Loesung.",
    facts:       ["Bezirk Hartberg-Fürstenfeld", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "Oststeiermark"],
    plzList:     ["8230", "8250"],
  },
  "fuerstenfeld": {
    name:        "Fürstenfeld",
    title:       "Holzpellets lose in Fürstenfeld",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Fürstenfeld, Bad Waltersdorf und Bad Blumau.",
    tagline:     "Lose Pellets fuer Fuerstenfeld",
    intro:       "Wenn Sie Holzpellets lose in Fuerstenfeld, Bad Waltersdorf oder Bad Blumau kaufen moechten, liefern wir die gewuenschte Menge direkt in Ihren Pellettank. So bleibt die Versorgung auch in der Heizsaison gut planbar.",
    highlight:   "In der Thermenregion sind fuer viele Haushalte eine saubere Lieferung, regionale Qualitaet und persoenliche Erreichbarkeit besonders wichtig. Genau darauf legen wir bei jeder Lieferung Wert.",
    facts:       ["Fürstenfeld & Thermenregion", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8280", "8282", "8283"],
  },
  "murau": {
    name:        "Murau",
    title:       "Holzpellets lose in Murau",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in den Bezirk Murau und in die obere Steiermark.",
    tagline:     "Lose Pellets fuer den Bezirk Murau",
    intro:       "Im Bezirk Murau ist Heizen mit Holz vielerorts vertraut. Wir liefern lose Holzpellets direkt in die Region und verbinden regionale Produktion mit einer praktischen Tankwagen-Lieferung fuer Haushalte und Betriebe.",
    highlight:   "Gerade in einer Holzregion wie Murau passen Pellets gut zu dem Wunsch nach erneuerbarer Waerme, kurzen Wegen und staerkerer Wertschoepfung in der Region.",
    facts:       ["Bezirk Murau", "4–5 Tage Lieferzeit", "Ab 3 Tonnen", "Holzregion"],
    plzList:     ["8850", "8851", "8852", "8861", "8862"],
  },
  "liezen": {
    name:        "Liezen",
    title:       "Holzpellets lose im Ennstal & Liezen",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in das Ennstal, nach Liezen, Schladming und Bad Aussee.",
    tagline:     "Lose Pellets fuer Liezen und das Ennstal",
    intro:       "In Liezen, Schladming, Bad Aussee und weiteren Orten im Ennstal liefern wir lose Holzpellets direkt per Tankwagen. Gerade in Regionen mit laengerer Heizperiode spielt eine verlaessliche Vorratsplanung eine grosse Rolle.",
    highlight:   "Ob Privathaus, Pension oder groesseres Objekt: Im Ennstal kommt es auf passende Mengen, saubere Befuellung und gut abgestimmte Liefertermine an. Genau dabei unterstuetzen wir.",
    facts:       ["Ennstal & Ausseerland", "4–6 Tage Lieferzeit", "Ab 3 Tonnen", "Tourismusregion"],
    plzList:     ["8940", "8950", "8960", "8970", "8971", "8990"],
  },
  "suedoststeiermark": {
    name:        "Südoststeiermark",
    title:       "Holzpellets lose in der Südoststeiermark",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose in die Südoststeiermark – Feldbach, Riegersburg, Bad Radkersburg.",
    tagline:     "Lose Pellets fuer die Suedoststeiermark",
    intro:       "Von Feldbach ueber Riegersburg bis Bad Radkersburg liefern wir lose Holzpellets in die Suedoststeiermark. Die Lieferung erfolgt direkt per Tankwagen und ist fuer viele Haushalte eine bequeme Alternative zum Nachfuellen von Sackware.",
    highlight:   "In der Suedoststeiermark spielen regionale Herkunft, persoenlicher Service und eine planbare Heizsaison fuer viele Kundinnen und Kunden eine wichtige Rolle. Daran orientiert sich auch unsere Lieferung.",
    facts:       ["Südoststeiermark", "4–6 Tage Lieferzeit", "Ab 3 Tonnen", "ENplus A1"],
    plzList:     ["8330", "8333", "8490", "8492", "8493"],
  },
  "kaernten": {
    name:        "Kärnten",
    title:       "Holzpellets lose in Kärnten",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose auch nach Kärnten – Klagenfurt und Umgebung.",
    tagline:     "Lose Pellets nach Kaernten auf Anfrage",
    intro:       "Auch nach Kaernten liefern wir lose Holzpellets auf Anfrage, vor allem im Raum Klagenfurt und Voelkermarkt. Weil die Wege laenger sind als in unserem Kerngebiet, stimmen wir Menge und Termin immer individuell ab.",
    highlight:   "Fuer Kundinnen und Kunden in Kaernten lohnt sich eine fruehzeitige Anfrage. So koennen wir Verfuegbarkeit, Lieferroute und passende Menge sauber einplanen.",
    facts:       ["Kärnten auf Anfrage", "5–7 Tage Lieferzeit", "Ab 5 Tonnen", "Mindermenge Aufschlag"],
    plzList:     ["9020", "9021", "9100"],
  },
  "wien": {
    name:        "Wien",
    title:       "Holzpellets lose in Wien",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose auch nach Wien – auf Anfrage für größere Mengen.",
    tagline:     "Lose Pellets nach Wien auf Anfrage",
    intro:       "Wien gehoert nicht zu unserem klassischen Kerngebiet, dennoch liefern wir lose Holzpellets auf Anfrage fuer groessere Mengen und passende Rahmenbedingungen. Dabei pruefen wir Lieferung und Transport individuell.",
    highlight:   "Wenn Sie in Wien Pellets kaufen moechten, ist ein kurzer Anruf am sinnvollsten. Dann klaeren wir direkt, ob Menge, Zufahrt und Lieferroute gut zusammenpassen.",
    facts:       ["Wien auf Anfrage", "5–7 Tage Lieferzeit", "Ab 10 Tonnen", "Bitte anrufen"],
    plzList:     ["1010", "1020", "1030", "1100", "1110", "1120", "1130", "1140", "1150", "1160", "1170", "1180", "1190", "1200", "1210", "1220", "1230"],
  },
  "niederoesterreich": {
    name:        "Niederösterreich",
    title:       "Holzpellets lose in Niederösterreich",
    description: "Steirer Pellets liefert ENplus A1 Holzpellets lose nach Niederösterreich – St. Pölten, Wiener Neustadt – auf Anfrage.",
    tagline:     "Lose Pellets nach Niederoesterreich auf Anfrage",
    intro:       "Nach Niederoesterreich liefern wir lose Holzpellets auf Anfrage, etwa in Richtung St. Poelten oder Wiener Neustadt. Weil diese Orte ausserhalb unseres regulaeren Kerngebiets liegen, stimmen wir jede Lieferung individuell ab.",
    highlight:   "Ein kurzer telefonischer Kontakt ist hier der beste Weg. So laesst sich schnell klaeren, welche Menge sinnvoll ist und ob die Lieferung in Ihr Gebiet gut planbar ist.",
    facts:       ["NÖ auf Anfrage", "6–8 Tage Lieferzeit", "Ab 10 Tonnen", "Bitte anrufen"],
    plzList:     ["3100", "2700"],
  },
};
